// Code generated by ent, DO NOT EDIT.

package webhookevent

import (
	"payment-gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldEventID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldEventType, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldAppID, v))
}

// GatewayOrderNo applies equality check predicate on the "gateway_order_no" field. It's identical to GatewayOrderNoEQ.
func GatewayOrderNo(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldGatewayOrderNo, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldPaymentOrderID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldEventID, v))
}

// EventIDContains applies the Contains predicate on the "event_id" field.
func EventIDContains(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContains(FieldEventID, v))
}

// EventIDHasPrefix applies the HasPrefix predicate on the "event_id" field.
func EventIDHasPrefix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasPrefix(FieldEventID, v))
}

// EventIDHasSuffix applies the HasSuffix predicate on the "event_id" field.
func EventIDHasSuffix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasSuffix(FieldEventID, v))
}

// EventIDEqualFold applies the EqualFold predicate on the "event_id" field.
func EventIDEqualFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEqualFold(FieldEventID, v))
}

// EventIDContainsFold applies the ContainsFold predicate on the "event_id" field.
func EventIDContainsFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContainsFold(FieldEventID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContainsFold(FieldEventType, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContainsFold(FieldAppID, v))
}

// GatewayOrderNoEQ applies the EQ predicate on the "gateway_order_no" field.
func GatewayOrderNoEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldGatewayOrderNo, v))
}

// GatewayOrderNoNEQ applies the NEQ predicate on the "gateway_order_no" field.
func GatewayOrderNoNEQ(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldGatewayOrderNo, v))
}

// GatewayOrderNoIn applies the In predicate on the "gateway_order_no" field.
func GatewayOrderNoIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldGatewayOrderNo, vs...))
}

// GatewayOrderNoNotIn applies the NotIn predicate on the "gateway_order_no" field.
func GatewayOrderNoNotIn(vs ...string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldGatewayOrderNo, vs...))
}

// GatewayOrderNoGT applies the GT predicate on the "gateway_order_no" field.
func GatewayOrderNoGT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldGatewayOrderNo, v))
}

// GatewayOrderNoGTE applies the GTE predicate on the "gateway_order_no" field.
func GatewayOrderNoGTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldGatewayOrderNo, v))
}

// GatewayOrderNoLT applies the LT predicate on the "gateway_order_no" field.
func GatewayOrderNoLT(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldGatewayOrderNo, v))
}

// GatewayOrderNoLTE applies the LTE predicate on the "gateway_order_no" field.
func GatewayOrderNoLTE(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldGatewayOrderNo, v))
}

// GatewayOrderNoContains applies the Contains predicate on the "gateway_order_no" field.
func GatewayOrderNoContains(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContains(FieldGatewayOrderNo, v))
}

// GatewayOrderNoHasPrefix applies the HasPrefix predicate on the "gateway_order_no" field.
func GatewayOrderNoHasPrefix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasPrefix(FieldGatewayOrderNo, v))
}

// GatewayOrderNoHasSuffix applies the HasSuffix predicate on the "gateway_order_no" field.
func GatewayOrderNoHasSuffix(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldHasSuffix(FieldGatewayOrderNo, v))
}

// GatewayOrderNoEqualFold applies the EqualFold predicate on the "gateway_order_no" field.
func GatewayOrderNoEqualFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEqualFold(FieldGatewayOrderNo, v))
}

// GatewayOrderNoContainsFold applies the ContainsFold predicate on the "gateway_order_no" field.
func GatewayOrderNoContainsFold(v string) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldContainsFold(FieldGatewayOrderNo, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDIsNil applies the IsNil predicate on the "payment_order_id" field.
func PaymentOrderIDIsNil() predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIsNull(FieldPaymentOrderID))
}

// PaymentOrderIDNotNil applies the NotNil predicate on the "payment_order_id" field.
func PaymentOrderIDNotNil() predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotNull(FieldPaymentOrderID))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotNull(FieldPayload))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebhookEvent) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebhookEvent) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebhookEvent) predicate.WebhookEvent {
	return predicate.WebhookEvent(sql.NotPredicates(p))
}
