// Code generated by ent, DO NOT EDIT.

package routingrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the routingrule type in the database.
	Label = "routing_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldAppScope holds the string denoting the app_scope field in the database.
	FieldAppScope = "app_scope"
	// FieldAppIds holds the string denoting the app_ids field in the database.
	FieldAppIds = "app_ids"
	// FieldPaymentMethod holds the string denoting the payment_method field in the database.
	FieldPaymentMethod = "payment_method"
	// FieldPayModes holds the string denoting the pay_modes field in the database.
	FieldPayModes = "pay_modes"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldMinAmount holds the string denoting the min_amount field in the database.
	FieldMinAmount = "min_amount"
	// FieldMaxAmount holds the string denoting the max_amount field in the database.
	FieldMaxAmount = "max_amount"
	// FieldTerminal holds the string denoting the terminal field in the database.
	FieldTerminal = "terminal"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the routingrule in the database.
	Table = "routing_rules"
)

// Columns holds all SQL columns for routingrule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEnabled,
	FieldPriority,
	FieldAppScope,
	FieldAppIds,
	FieldPaymentMethod,
	FieldPayModes,
	FieldCurrency,
	FieldMinAmount,
	FieldMaxAmount,
	FieldTerminal,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultAppScope holds the default value on creation for the "app_scope" field.
	DefaultAppScope string
	// DefaultMinAmount holds the default value on creation for the "min_amount" field.
	DefaultMinAmount int64
	// DefaultMaxAmount holds the default value on creation for the "max_amount" field.
	DefaultMaxAmount int64
	// DefaultTerminal holds the default value on creation for the "terminal" field.
	DefaultTerminal string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RoutingRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByAppScope orders the results by the app_scope field.
func ByAppScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppScope, opts...).ToFunc()
}

// ByPaymentMethod orders the results by the payment_method field.
func ByPaymentMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentMethod, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByMinAmount orders the results by the min_amount field.
func ByMinAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinAmount, opts...).ToFunc()
}

// ByMaxAmount orders the results by the max_amount field.
func ByMaxAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAmount, opts...).ToFunc()
}

// ByTerminal orders the results by the terminal field.
func ByTerminal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTerminal, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
