// Code generated by ent, DO NOT EDIT.

package routingrule

import (
	"payment-gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldPriority, v))
}

// AppScope applies equality check predicate on the "app_scope" field. It's identical to AppScopeEQ.
func AppScope(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldAppScope, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldPaymentMethod, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldCurrency, v))
}

// MinAmount applies equality check predicate on the "min_amount" field. It's identical to MinAmountEQ.
func MinAmount(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldMinAmount, v))
}

// MaxAmount applies equality check predicate on the "max_amount" field. It's identical to MaxAmountEQ.
func MaxAmount(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldMaxAmount, v))
}

// Terminal applies equality check predicate on the "terminal" field. It's identical to TerminalEQ.
func Terminal(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldTerminal, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldPriority, v))
}

// AppScopeEQ applies the EQ predicate on the "app_scope" field.
func AppScopeEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldAppScope, v))
}

// AppScopeNEQ applies the NEQ predicate on the "app_scope" field.
func AppScopeNEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldAppScope, v))
}

// AppScopeIn applies the In predicate on the "app_scope" field.
func AppScopeIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldAppScope, vs...))
}

// AppScopeNotIn applies the NotIn predicate on the "app_scope" field.
func AppScopeNotIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldAppScope, vs...))
}

// AppScopeGT applies the GT predicate on the "app_scope" field.
func AppScopeGT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldAppScope, v))
}

// AppScopeGTE applies the GTE predicate on the "app_scope" field.
func AppScopeGTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldAppScope, v))
}

// AppScopeLT applies the LT predicate on the "app_scope" field.
func AppScopeLT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldAppScope, v))
}

// AppScopeLTE applies the LTE predicate on the "app_scope" field.
func AppScopeLTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldAppScope, v))
}

// AppScopeContains applies the Contains predicate on the "app_scope" field.
func AppScopeContains(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContains(FieldAppScope, v))
}

// AppScopeHasPrefix applies the HasPrefix predicate on the "app_scope" field.
func AppScopeHasPrefix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasPrefix(FieldAppScope, v))
}

// AppScopeHasSuffix applies the HasSuffix predicate on the "app_scope" field.
func AppScopeHasSuffix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasSuffix(FieldAppScope, v))
}

// AppScopeEqualFold applies the EqualFold predicate on the "app_scope" field.
func AppScopeEqualFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEqualFold(FieldAppScope, v))
}

// AppScopeContainsFold applies the ContainsFold predicate on the "app_scope" field.
func AppScopeContainsFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContainsFold(FieldAppScope, v))
}

// AppIdsIsNil applies the IsNil predicate on the "app_ids" field.
func AppIdsIsNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIsNull(FieldAppIds))
}

// AppIdsNotNil applies the NotNil predicate on the "app_ids" field.
func AppIdsNotNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotNull(FieldAppIds))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// PayModesIsNil applies the IsNil predicate on the "pay_modes" field.
func PayModesIsNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIsNull(FieldPayModes))
}

// PayModesNotNil applies the NotNil predicate on the "pay_modes" field.
func PayModesNotNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotNull(FieldPayModes))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyIsNil applies the IsNil predicate on the "currency" field.
func CurrencyIsNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIsNull(FieldCurrency))
}

// CurrencyNotNil applies the NotNil predicate on the "currency" field.
func CurrencyNotNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotNull(FieldCurrency))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContainsFold(FieldCurrency, v))
}

// MinAmountEQ applies the EQ predicate on the "min_amount" field.
func MinAmountEQ(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldMinAmount, v))
}

// MinAmountNEQ applies the NEQ predicate on the "min_amount" field.
func MinAmountNEQ(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldMinAmount, v))
}

// MinAmountIn applies the In predicate on the "min_amount" field.
func MinAmountIn(vs ...int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldMinAmount, vs...))
}

// MinAmountNotIn applies the NotIn predicate on the "min_amount" field.
func MinAmountNotIn(vs ...int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldMinAmount, vs...))
}

// MinAmountGT applies the GT predicate on the "min_amount" field.
func MinAmountGT(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldMinAmount, v))
}

// MinAmountGTE applies the GTE predicate on the "min_amount" field.
func MinAmountGTE(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldMinAmount, v))
}

// MinAmountLT applies the LT predicate on the "min_amount" field.
func MinAmountLT(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldMinAmount, v))
}

// MinAmountLTE applies the LTE predicate on the "min_amount" field.
func MinAmountLTE(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldMinAmount, v))
}

// MaxAmountEQ applies the EQ predicate on the "max_amount" field.
func MaxAmountEQ(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldMaxAmount, v))
}

// MaxAmountNEQ applies the NEQ predicate on the "max_amount" field.
func MaxAmountNEQ(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldMaxAmount, v))
}

// MaxAmountIn applies the In predicate on the "max_amount" field.
func MaxAmountIn(vs ...int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldMaxAmount, vs...))
}

// MaxAmountNotIn applies the NotIn predicate on the "max_amount" field.
func MaxAmountNotIn(vs ...int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldMaxAmount, vs...))
}

// MaxAmountGT applies the GT predicate on the "max_amount" field.
func MaxAmountGT(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldMaxAmount, v))
}

// MaxAmountGTE applies the GTE predicate on the "max_amount" field.
func MaxAmountGTE(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldMaxAmount, v))
}

// MaxAmountLT applies the LT predicate on the "max_amount" field.
func MaxAmountLT(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldMaxAmount, v))
}

// MaxAmountLTE applies the LTE predicate on the "max_amount" field.
func MaxAmountLTE(v int64) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldMaxAmount, v))
}

// TerminalEQ applies the EQ predicate on the "terminal" field.
func TerminalEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldTerminal, v))
}

// TerminalNEQ applies the NEQ predicate on the "terminal" field.
func TerminalNEQ(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldTerminal, v))
}

// TerminalIn applies the In predicate on the "terminal" field.
func TerminalIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldTerminal, vs...))
}

// TerminalNotIn applies the NotIn predicate on the "terminal" field.
func TerminalNotIn(vs ...string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldTerminal, vs...))
}

// TerminalGT applies the GT predicate on the "terminal" field.
func TerminalGT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldTerminal, v))
}

// TerminalGTE applies the GTE predicate on the "terminal" field.
func TerminalGTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldTerminal, v))
}

// TerminalLT applies the LT predicate on the "terminal" field.
func TerminalLT(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldTerminal, v))
}

// TerminalLTE applies the LTE predicate on the "terminal" field.
func TerminalLTE(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldTerminal, v))
}

// TerminalContains applies the Contains predicate on the "terminal" field.
func TerminalContains(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContains(FieldTerminal, v))
}

// TerminalHasPrefix applies the HasPrefix predicate on the "terminal" field.
func TerminalHasPrefix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasPrefix(FieldTerminal, v))
}

// TerminalHasSuffix applies the HasSuffix predicate on the "terminal" field.
func TerminalHasSuffix(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldHasSuffix(FieldTerminal, v))
}

// TerminalEqualFold applies the EqualFold predicate on the "terminal" field.
func TerminalEqualFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEqualFold(FieldTerminal, v))
}

// TerminalContainsFold applies the ContainsFold predicate on the "terminal" field.
func TerminalContainsFold(v string) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldContainsFold(FieldTerminal, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RoutingRule {
	return predicate.RoutingRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoutingRule) predicate.RoutingRule {
	return predicate.RoutingRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoutingRule) predicate.RoutingRule {
	return predicate.RoutingRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoutingRule) predicate.RoutingRule {
	return predicate.RoutingRule(sql.NotPredicates(p))
}
