// Code generated by ent, DO NOT EDIT.

package gatewayconfig

import (
	"payment-gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldID, id))
}

// SiteName applies equality check predicate on the "site_name" field. It's identical to SiteNameEQ.
func SiteName(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldSiteName, v))
}

// GatewayBaseURL applies equality check predicate on the "gateway_base_url" field. It's identical to GatewayBaseURLEQ.
func GatewayBaseURL(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldGatewayBaseURL, v))
}

// PaymentNotifyPath applies equality check predicate on the "payment_notify_path" field. It's identical to PaymentNotifyPathEQ.
func PaymentNotifyPath(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldPaymentNotifyPath, v))
}

// DefaultCurrency applies equality check predicate on the "default_currency" field. It's identical to DefaultCurrencyEQ.
func DefaultCurrency(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldDefaultCurrency, v))
}

// DefaultLocale applies equality check predicate on the "default_locale" field. It's identical to DefaultLocaleEQ.
func DefaultLocale(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldDefaultLocale, v))
}

// RequestIDEnabled applies equality check predicate on the "request_id_enabled" field. It's identical to RequestIDEnabledEQ.
func RequestIDEnabled(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldRequestIDEnabled, v))
}

// MaintenanceMode applies equality check predicate on the "maintenance_mode" field. It's identical to MaintenanceModeEQ.
func MaintenanceMode(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldMaintenanceMode, v))
}

// OrderDefaultTTLSeconds applies equality check predicate on the "order_default_ttl_seconds" field. It's identical to OrderDefaultTTLSecondsEQ.
func OrderDefaultTTLSeconds(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderDefaultTTLSeconds, v))
}

// OrderExpireScanIntervalSeconds applies equality check predicate on the "order_expire_scan_interval_seconds" field. It's identical to OrderExpireScanIntervalSecondsEQ.
func OrderExpireScanIntervalSeconds(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderExpireScanIntervalSeconds, v))
}

// OrderExpireScanLimit applies equality check predicate on the "order_expire_scan_limit" field. It's identical to OrderExpireScanLimitEQ.
func OrderExpireScanLimit(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderExpireScanLimit, v))
}

// OrderExpireWorkerConcurrency applies equality check predicate on the "order_expire_worker_concurrency" field. It's identical to OrderExpireWorkerConcurrencyEQ.
func OrderExpireWorkerConcurrency(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderExpireWorkerConcurrency, v))
}

// OpenAPIRateLimitEnabled applies equality check predicate on the "open_api_rate_limit_enabled" field. It's identical to OpenAPIRateLimitEnabledEQ.
func OpenAPIRateLimitEnabled(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOpenAPIRateLimitEnabled, v))
}

// OpenAPIRateLimit applies equality check predicate on the "open_api_rate_limit" field. It's identical to OpenAPIRateLimitEQ.
func OpenAPIRateLimit(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOpenAPIRateLimit, v))
}

// OpenAPIRateLimitWindowSeconds applies equality check predicate on the "open_api_rate_limit_window_seconds" field. It's identical to OpenAPIRateLimitWindowSecondsEQ.
func OpenAPIRateLimitWindowSeconds(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOpenAPIRateLimitWindowSeconds, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// SiteNameEQ applies the EQ predicate on the "site_name" field.
func SiteNameEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldSiteName, v))
}

// SiteNameNEQ applies the NEQ predicate on the "site_name" field.
func SiteNameNEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldSiteName, v))
}

// SiteNameIn applies the In predicate on the "site_name" field.
func SiteNameIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldSiteName, vs...))
}

// SiteNameNotIn applies the NotIn predicate on the "site_name" field.
func SiteNameNotIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldSiteName, vs...))
}

// SiteNameGT applies the GT predicate on the "site_name" field.
func SiteNameGT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldSiteName, v))
}

// SiteNameGTE applies the GTE predicate on the "site_name" field.
func SiteNameGTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldSiteName, v))
}

// SiteNameLT applies the LT predicate on the "site_name" field.
func SiteNameLT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldSiteName, v))
}

// SiteNameLTE applies the LTE predicate on the "site_name" field.
func SiteNameLTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldSiteName, v))
}

// SiteNameContains applies the Contains predicate on the "site_name" field.
func SiteNameContains(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContains(FieldSiteName, v))
}

// SiteNameHasPrefix applies the HasPrefix predicate on the "site_name" field.
func SiteNameHasPrefix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasPrefix(FieldSiteName, v))
}

// SiteNameHasSuffix applies the HasSuffix predicate on the "site_name" field.
func SiteNameHasSuffix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasSuffix(FieldSiteName, v))
}

// SiteNameEqualFold applies the EqualFold predicate on the "site_name" field.
func SiteNameEqualFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEqualFold(FieldSiteName, v))
}

// SiteNameContainsFold applies the ContainsFold predicate on the "site_name" field.
func SiteNameContainsFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContainsFold(FieldSiteName, v))
}

// GatewayBaseURLEQ applies the EQ predicate on the "gateway_base_url" field.
func GatewayBaseURLEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldGatewayBaseURL, v))
}

// GatewayBaseURLNEQ applies the NEQ predicate on the "gateway_base_url" field.
func GatewayBaseURLNEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldGatewayBaseURL, v))
}

// GatewayBaseURLIn applies the In predicate on the "gateway_base_url" field.
func GatewayBaseURLIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldGatewayBaseURL, vs...))
}

// GatewayBaseURLNotIn applies the NotIn predicate on the "gateway_base_url" field.
func GatewayBaseURLNotIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldGatewayBaseURL, vs...))
}

// GatewayBaseURLGT applies the GT predicate on the "gateway_base_url" field.
func GatewayBaseURLGT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldGatewayBaseURL, v))
}

// GatewayBaseURLGTE applies the GTE predicate on the "gateway_base_url" field.
func GatewayBaseURLGTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldGatewayBaseURL, v))
}

// GatewayBaseURLLT applies the LT predicate on the "gateway_base_url" field.
func GatewayBaseURLLT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldGatewayBaseURL, v))
}

// GatewayBaseURLLTE applies the LTE predicate on the "gateway_base_url" field.
func GatewayBaseURLLTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldGatewayBaseURL, v))
}

// GatewayBaseURLContains applies the Contains predicate on the "gateway_base_url" field.
func GatewayBaseURLContains(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContains(FieldGatewayBaseURL, v))
}

// GatewayBaseURLHasPrefix applies the HasPrefix predicate on the "gateway_base_url" field.
func GatewayBaseURLHasPrefix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasPrefix(FieldGatewayBaseURL, v))
}

// GatewayBaseURLHasSuffix applies the HasSuffix predicate on the "gateway_base_url" field.
func GatewayBaseURLHasSuffix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasSuffix(FieldGatewayBaseURL, v))
}

// GatewayBaseURLEqualFold applies the EqualFold predicate on the "gateway_base_url" field.
func GatewayBaseURLEqualFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEqualFold(FieldGatewayBaseURL, v))
}

// GatewayBaseURLContainsFold applies the ContainsFold predicate on the "gateway_base_url" field.
func GatewayBaseURLContainsFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContainsFold(FieldGatewayBaseURL, v))
}

// PaymentNotifyPathEQ applies the EQ predicate on the "payment_notify_path" field.
func PaymentNotifyPathEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathNEQ applies the NEQ predicate on the "payment_notify_path" field.
func PaymentNotifyPathNEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathIn applies the In predicate on the "payment_notify_path" field.
func PaymentNotifyPathIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldPaymentNotifyPath, vs...))
}

// PaymentNotifyPathNotIn applies the NotIn predicate on the "payment_notify_path" field.
func PaymentNotifyPathNotIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldPaymentNotifyPath, vs...))
}

// PaymentNotifyPathGT applies the GT predicate on the "payment_notify_path" field.
func PaymentNotifyPathGT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathGTE applies the GTE predicate on the "payment_notify_path" field.
func PaymentNotifyPathGTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathLT applies the LT predicate on the "payment_notify_path" field.
func PaymentNotifyPathLT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathLTE applies the LTE predicate on the "payment_notify_path" field.
func PaymentNotifyPathLTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathContains applies the Contains predicate on the "payment_notify_path" field.
func PaymentNotifyPathContains(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContains(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathHasPrefix applies the HasPrefix predicate on the "payment_notify_path" field.
func PaymentNotifyPathHasPrefix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasPrefix(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathHasSuffix applies the HasSuffix predicate on the "payment_notify_path" field.
func PaymentNotifyPathHasSuffix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasSuffix(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathEqualFold applies the EqualFold predicate on the "payment_notify_path" field.
func PaymentNotifyPathEqualFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEqualFold(FieldPaymentNotifyPath, v))
}

// PaymentNotifyPathContainsFold applies the ContainsFold predicate on the "payment_notify_path" field.
func PaymentNotifyPathContainsFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContainsFold(FieldPaymentNotifyPath, v))
}

// DefaultCurrencyEQ applies the EQ predicate on the "default_currency" field.
func DefaultCurrencyEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldDefaultCurrency, v))
}

// DefaultCurrencyNEQ applies the NEQ predicate on the "default_currency" field.
func DefaultCurrencyNEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldDefaultCurrency, v))
}

// DefaultCurrencyIn applies the In predicate on the "default_currency" field.
func DefaultCurrencyIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldDefaultCurrency, vs...))
}

// DefaultCurrencyNotIn applies the NotIn predicate on the "default_currency" field.
func DefaultCurrencyNotIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldDefaultCurrency, vs...))
}

// DefaultCurrencyGT applies the GT predicate on the "default_currency" field.
func DefaultCurrencyGT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldDefaultCurrency, v))
}

// DefaultCurrencyGTE applies the GTE predicate on the "default_currency" field.
func DefaultCurrencyGTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldDefaultCurrency, v))
}

// DefaultCurrencyLT applies the LT predicate on the "default_currency" field.
func DefaultCurrencyLT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldDefaultCurrency, v))
}

// DefaultCurrencyLTE applies the LTE predicate on the "default_currency" field.
func DefaultCurrencyLTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldDefaultCurrency, v))
}

// DefaultCurrencyContains applies the Contains predicate on the "default_currency" field.
func DefaultCurrencyContains(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContains(FieldDefaultCurrency, v))
}

// DefaultCurrencyHasPrefix applies the HasPrefix predicate on the "default_currency" field.
func DefaultCurrencyHasPrefix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasPrefix(FieldDefaultCurrency, v))
}

// DefaultCurrencyHasSuffix applies the HasSuffix predicate on the "default_currency" field.
func DefaultCurrencyHasSuffix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasSuffix(FieldDefaultCurrency, v))
}

// DefaultCurrencyEqualFold applies the EqualFold predicate on the "default_currency" field.
func DefaultCurrencyEqualFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEqualFold(FieldDefaultCurrency, v))
}

// DefaultCurrencyContainsFold applies the ContainsFold predicate on the "default_currency" field.
func DefaultCurrencyContainsFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContainsFold(FieldDefaultCurrency, v))
}

// DefaultLocaleEQ applies the EQ predicate on the "default_locale" field.
func DefaultLocaleEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldDefaultLocale, v))
}

// DefaultLocaleNEQ applies the NEQ predicate on the "default_locale" field.
func DefaultLocaleNEQ(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldDefaultLocale, v))
}

// DefaultLocaleIn applies the In predicate on the "default_locale" field.
func DefaultLocaleIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldDefaultLocale, vs...))
}

// DefaultLocaleNotIn applies the NotIn predicate on the "default_locale" field.
func DefaultLocaleNotIn(vs ...string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldDefaultLocale, vs...))
}

// DefaultLocaleGT applies the GT predicate on the "default_locale" field.
func DefaultLocaleGT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldDefaultLocale, v))
}

// DefaultLocaleGTE applies the GTE predicate on the "default_locale" field.
func DefaultLocaleGTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldDefaultLocale, v))
}

// DefaultLocaleLT applies the LT predicate on the "default_locale" field.
func DefaultLocaleLT(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldDefaultLocale, v))
}

// DefaultLocaleLTE applies the LTE predicate on the "default_locale" field.
func DefaultLocaleLTE(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldDefaultLocale, v))
}

// DefaultLocaleContains applies the Contains predicate on the "default_locale" field.
func DefaultLocaleContains(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContains(FieldDefaultLocale, v))
}

// DefaultLocaleHasPrefix applies the HasPrefix predicate on the "default_locale" field.
func DefaultLocaleHasPrefix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasPrefix(FieldDefaultLocale, v))
}

// DefaultLocaleHasSuffix applies the HasSuffix predicate on the "default_locale" field.
func DefaultLocaleHasSuffix(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldHasSuffix(FieldDefaultLocale, v))
}

// DefaultLocaleEqualFold applies the EqualFold predicate on the "default_locale" field.
func DefaultLocaleEqualFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEqualFold(FieldDefaultLocale, v))
}

// DefaultLocaleContainsFold applies the ContainsFold predicate on the "default_locale" field.
func DefaultLocaleContainsFold(v string) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldContainsFold(FieldDefaultLocale, v))
}

// RequestIDEnabledEQ applies the EQ predicate on the "request_id_enabled" field.
func RequestIDEnabledEQ(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldRequestIDEnabled, v))
}

// RequestIDEnabledNEQ applies the NEQ predicate on the "request_id_enabled" field.
func RequestIDEnabledNEQ(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldRequestIDEnabled, v))
}

// MaintenanceModeEQ applies the EQ predicate on the "maintenance_mode" field.
func MaintenanceModeEQ(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldMaintenanceMode, v))
}

// MaintenanceModeNEQ applies the NEQ predicate on the "maintenance_mode" field.
func MaintenanceModeNEQ(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldMaintenanceMode, v))
}

// OrderDefaultTTLSecondsEQ applies the EQ predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderDefaultTTLSeconds, v))
}

// OrderDefaultTTLSecondsNEQ applies the NEQ predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsNEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldOrderDefaultTTLSeconds, v))
}

// OrderDefaultTTLSecondsIn applies the In predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldOrderDefaultTTLSeconds, vs...))
}

// OrderDefaultTTLSecondsNotIn applies the NotIn predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsNotIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldOrderDefaultTTLSeconds, vs...))
}

// OrderDefaultTTLSecondsGT applies the GT predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsGT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldOrderDefaultTTLSeconds, v))
}

// OrderDefaultTTLSecondsGTE applies the GTE predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsGTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldOrderDefaultTTLSeconds, v))
}

// OrderDefaultTTLSecondsLT applies the LT predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsLT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldOrderDefaultTTLSeconds, v))
}

// OrderDefaultTTLSecondsLTE applies the LTE predicate on the "order_default_ttl_seconds" field.
func OrderDefaultTTLSecondsLTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldOrderDefaultTTLSeconds, v))
}

// OrderExpireScanIntervalSecondsEQ applies the EQ predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderExpireScanIntervalSeconds, v))
}

// OrderExpireScanIntervalSecondsNEQ applies the NEQ predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsNEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldOrderExpireScanIntervalSeconds, v))
}

// OrderExpireScanIntervalSecondsIn applies the In predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldOrderExpireScanIntervalSeconds, vs...))
}

// OrderExpireScanIntervalSecondsNotIn applies the NotIn predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsNotIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldOrderExpireScanIntervalSeconds, vs...))
}

// OrderExpireScanIntervalSecondsGT applies the GT predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsGT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldOrderExpireScanIntervalSeconds, v))
}

// OrderExpireScanIntervalSecondsGTE applies the GTE predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsGTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldOrderExpireScanIntervalSeconds, v))
}

// OrderExpireScanIntervalSecondsLT applies the LT predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsLT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldOrderExpireScanIntervalSeconds, v))
}

// OrderExpireScanIntervalSecondsLTE applies the LTE predicate on the "order_expire_scan_interval_seconds" field.
func OrderExpireScanIntervalSecondsLTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldOrderExpireScanIntervalSeconds, v))
}

// OrderExpireScanLimitEQ applies the EQ predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderExpireScanLimit, v))
}

// OrderExpireScanLimitNEQ applies the NEQ predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitNEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldOrderExpireScanLimit, v))
}

// OrderExpireScanLimitIn applies the In predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldOrderExpireScanLimit, vs...))
}

// OrderExpireScanLimitNotIn applies the NotIn predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitNotIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldOrderExpireScanLimit, vs...))
}

// OrderExpireScanLimitGT applies the GT predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitGT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldOrderExpireScanLimit, v))
}

// OrderExpireScanLimitGTE applies the GTE predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitGTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldOrderExpireScanLimit, v))
}

// OrderExpireScanLimitLT applies the LT predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitLT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldOrderExpireScanLimit, v))
}

// OrderExpireScanLimitLTE applies the LTE predicate on the "order_expire_scan_limit" field.
func OrderExpireScanLimitLTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldOrderExpireScanLimit, v))
}

// OrderExpireWorkerConcurrencyEQ applies the EQ predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOrderExpireWorkerConcurrency, v))
}

// OrderExpireWorkerConcurrencyNEQ applies the NEQ predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyNEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldOrderExpireWorkerConcurrency, v))
}

// OrderExpireWorkerConcurrencyIn applies the In predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldOrderExpireWorkerConcurrency, vs...))
}

// OrderExpireWorkerConcurrencyNotIn applies the NotIn predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyNotIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldOrderExpireWorkerConcurrency, vs...))
}

// OrderExpireWorkerConcurrencyGT applies the GT predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyGT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldOrderExpireWorkerConcurrency, v))
}

// OrderExpireWorkerConcurrencyGTE applies the GTE predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyGTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldOrderExpireWorkerConcurrency, v))
}

// OrderExpireWorkerConcurrencyLT applies the LT predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyLT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldOrderExpireWorkerConcurrency, v))
}

// OrderExpireWorkerConcurrencyLTE applies the LTE predicate on the "order_expire_worker_concurrency" field.
func OrderExpireWorkerConcurrencyLTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldOrderExpireWorkerConcurrency, v))
}

// OpenAPIRateLimitEnabledEQ applies the EQ predicate on the "open_api_rate_limit_enabled" field.
func OpenAPIRateLimitEnabledEQ(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOpenAPIRateLimitEnabled, v))
}

// OpenAPIRateLimitEnabledNEQ applies the NEQ predicate on the "open_api_rate_limit_enabled" field.
func OpenAPIRateLimitEnabledNEQ(v bool) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldOpenAPIRateLimitEnabled, v))
}

// OpenAPIRateLimitEQ applies the EQ predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOpenAPIRateLimit, v))
}

// OpenAPIRateLimitNEQ applies the NEQ predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitNEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldOpenAPIRateLimit, v))
}

// OpenAPIRateLimitIn applies the In predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldOpenAPIRateLimit, vs...))
}

// OpenAPIRateLimitNotIn applies the NotIn predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitNotIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldOpenAPIRateLimit, vs...))
}

// OpenAPIRateLimitGT applies the GT predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitGT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldOpenAPIRateLimit, v))
}

// OpenAPIRateLimitGTE applies the GTE predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitGTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldOpenAPIRateLimit, v))
}

// OpenAPIRateLimitLT applies the LT predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitLT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldOpenAPIRateLimit, v))
}

// OpenAPIRateLimitLTE applies the LTE predicate on the "open_api_rate_limit" field.
func OpenAPIRateLimitLTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldOpenAPIRateLimit, v))
}

// OpenAPIRateLimitWindowSecondsEQ applies the EQ predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldOpenAPIRateLimitWindowSeconds, v))
}

// OpenAPIRateLimitWindowSecondsNEQ applies the NEQ predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsNEQ(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldOpenAPIRateLimitWindowSeconds, v))
}

// OpenAPIRateLimitWindowSecondsIn applies the In predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldOpenAPIRateLimitWindowSeconds, vs...))
}

// OpenAPIRateLimitWindowSecondsNotIn applies the NotIn predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsNotIn(vs ...int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldOpenAPIRateLimitWindowSeconds, vs...))
}

// OpenAPIRateLimitWindowSecondsGT applies the GT predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsGT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldOpenAPIRateLimitWindowSeconds, v))
}

// OpenAPIRateLimitWindowSecondsGTE applies the GTE predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsGTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldOpenAPIRateLimitWindowSeconds, v))
}

// OpenAPIRateLimitWindowSecondsLT applies the LT predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsLT(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldOpenAPIRateLimitWindowSeconds, v))
}

// OpenAPIRateLimitWindowSecondsLTE applies the LTE predicate on the "open_api_rate_limit_window_seconds" field.
func OpenAPIRateLimitWindowSecondsLTE(v int) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldOpenAPIRateLimitWindowSeconds, v))
}

// ExtraIsNil applies the IsNil predicate on the "extra" field.
func ExtraIsNil() predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIsNull(FieldExtra))
}

// ExtraNotNil applies the NotNil predicate on the "extra" field.
func ExtraNotNil() predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotNull(FieldExtra))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GatewayConfig) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GatewayConfig) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GatewayConfig) predicate.GatewayConfig {
	return predicate.GatewayConfig(sql.NotPredicates(p))
}
