// Code generated by ent, DO NOT EDIT.

package paymentreconciliation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentreconciliation type in the database.
	Label = "payment_reconciliation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldGatewayOrderNo holds the string denoting the gateway_order_no field in the database.
	FieldGatewayOrderNo = "gateway_order_no"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldChannelAccountID holds the string denoting the channel_account_id field in the database.
	FieldChannelAccountID = "channel_account_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldLastAttemptAt holds the string denoting the last_attempt_at field in the database.
	FieldLastAttemptAt = "last_attempt_at"
	// FieldActiveQueryRequestedAt holds the string denoting the active_query_requested_at field in the database.
	FieldActiveQueryRequestedAt = "active_query_requested_at"
	// FieldLastProviderStatus holds the string denoting the last_provider_status field in the database.
	FieldLastProviderStatus = "last_provider_status"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldProviderSnapshot holds the string denoting the provider_snapshot field in the database.
	FieldProviderSnapshot = "provider_snapshot"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentreconciliation in the database.
	Table = "payment_reconciliations"
)

// Columns holds all SQL columns for paymentreconciliation fields.
var Columns = []string{
	FieldID,
	FieldPaymentOrderID,
	FieldGatewayOrderNo,
	FieldChannel,
	FieldChannelAccountID,
	FieldStatus,
	FieldAttemptCount,
	FieldNextAttemptAt,
	FieldLastAttemptAt,
	FieldActiveQueryRequestedAt,
	FieldLastProviderStatus,
	FieldLastError,
	FieldProviderSnapshot,
	FieldResolvedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentReconciliation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByGatewayOrderNo orders the results by the gateway_order_no field.
func ByGatewayOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayOrderNo, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByChannelAccountID orders the results by the channel_account_id field.
func ByChannelAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelAccountID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByLastAttemptAt orders the results by the last_attempt_at field.
func ByLastAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAttemptAt, opts...).ToFunc()
}

// ByActiveQueryRequestedAt orders the results by the active_query_requested_at field.
func ByActiveQueryRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveQueryRequestedAt, opts...).ToFunc()
}

// ByLastProviderStatus orders the results by the last_provider_status field.
func ByLastProviderStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProviderStatus, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
