// Code generated by ent, DO NOT EDIT.

package refund

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the refund type in the database.
	Label = "refund"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRefundNo holds the string denoting the refund_no field in the database.
	FieldRefundNo = "refund_no"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldGatewayOrderNo holds the string denoting the gateway_order_no field in the database.
	FieldGatewayOrderNo = "gateway_order_no"
	// FieldMerchantOrderNo holds the string denoting the merchant_order_no field in the database.
	FieldMerchantOrderNo = "merchant_order_no"
	// FieldMerchantRefundNo holds the string denoting the merchant_refund_no field in the database.
	FieldMerchantRefundNo = "merchant_refund_no"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldChannelAccountID holds the string denoting the channel_account_id field in the database.
	FieldChannelAccountID = "channel_account_id"
	// FieldProviderOrderNo holds the string denoting the provider_order_no field in the database.
	FieldProviderOrderNo = "provider_order_no"
	// FieldChannelTradeNo holds the string denoting the channel_trade_no field in the database.
	FieldChannelTradeNo = "channel_trade_no"
	// FieldChannelRefundNo holds the string denoting the channel_refund_no field in the database.
	FieldChannelRefundNo = "channel_refund_no"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldProviderSnapshot holds the string denoting the provider_snapshot field in the database.
	FieldProviderSnapshot = "provider_snapshot"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldLastAttemptAt holds the string denoting the last_attempt_at field in the database.
	FieldLastAttemptAt = "last_attempt_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldSucceededAt holds the string denoting the succeeded_at field in the database.
	FieldSucceededAt = "succeeded_at"
	// FieldFailedAt holds the string denoting the failed_at field in the database.
	FieldFailedAt = "failed_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the refund in the database.
	Table = "refunds"
)

// Columns holds all SQL columns for refund fields.
var Columns = []string{
	FieldID,
	FieldRefundNo,
	FieldAppID,
	FieldPaymentOrderID,
	FieldGatewayOrderNo,
	FieldMerchantOrderNo,
	FieldMerchantRefundNo,
	FieldChannel,
	FieldChannelAccountID,
	FieldProviderOrderNo,
	FieldChannelTradeNo,
	FieldChannelRefundNo,
	FieldAmount,
	FieldCurrency,
	FieldReason,
	FieldStatus,
	FieldFailureReason,
	FieldMetadata,
	FieldProviderSnapshot,
	FieldAttemptCount,
	FieldNextAttemptAt,
	FieldLastAttemptAt,
	FieldLastError,
	FieldSucceededAt,
	FieldFailedAt,
	FieldClosedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Refund queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRefundNo orders the results by the refund_no field.
func ByRefundNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundNo, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByGatewayOrderNo orders the results by the gateway_order_no field.
func ByGatewayOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayOrderNo, opts...).ToFunc()
}

// ByMerchantOrderNo orders the results by the merchant_order_no field.
func ByMerchantOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantOrderNo, opts...).ToFunc()
}

// ByMerchantRefundNo orders the results by the merchant_refund_no field.
func ByMerchantRefundNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantRefundNo, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByChannelAccountID orders the results by the channel_account_id field.
func ByChannelAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelAccountID, opts...).ToFunc()
}

// ByProviderOrderNo orders the results by the provider_order_no field.
func ByProviderOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderOrderNo, opts...).ToFunc()
}

// ByChannelTradeNo orders the results by the channel_trade_no field.
func ByChannelTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelTradeNo, opts...).ToFunc()
}

// ByChannelRefundNo orders the results by the channel_refund_no field.
func ByChannelRefundNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelRefundNo, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByLastAttemptAt orders the results by the last_attempt_at field.
func ByLastAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAttemptAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// BySucceededAt orders the results by the succeeded_at field.
func BySucceededAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSucceededAt, opts...).ToFunc()
}

// ByFailedAt orders the results by the failed_at field.
func ByFailedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
