// Code generated by ent, DO NOT EDIT.

package refund

import (
	"payment-gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldID, id))
}

// RefundNo applies equality check predicate on the "refund_no" field. It's identical to RefundNoEQ.
func RefundNo(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldRefundNo, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldAppID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldPaymentOrderID, v))
}

// GatewayOrderNo applies equality check predicate on the "gateway_order_no" field. It's identical to GatewayOrderNoEQ.
func GatewayOrderNo(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldGatewayOrderNo, v))
}

// MerchantOrderNo applies equality check predicate on the "merchant_order_no" field. It's identical to MerchantOrderNoEQ.
func MerchantOrderNo(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldMerchantOrderNo, v))
}

// MerchantRefundNo applies equality check predicate on the "merchant_refund_no" field. It's identical to MerchantRefundNoEQ.
func MerchantRefundNo(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldMerchantRefundNo, v))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannel, v))
}

// ChannelAccountID applies equality check predicate on the "channel_account_id" field. It's identical to ChannelAccountIDEQ.
func ChannelAccountID(v int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannelAccountID, v))
}

// ProviderOrderNo applies equality check predicate on the "provider_order_no" field. It's identical to ProviderOrderNoEQ.
func ProviderOrderNo(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldProviderOrderNo, v))
}

// ChannelTradeNo applies equality check predicate on the "channel_trade_no" field. It's identical to ChannelTradeNoEQ.
func ChannelTradeNo(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannelTradeNo, v))
}

// ChannelRefundNo applies equality check predicate on the "channel_refund_no" field. It's identical to ChannelRefundNoEQ.
func ChannelRefundNo(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannelRefundNo, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldCurrency, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldStatus, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldFailureReason, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldAttemptCount, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldNextAttemptAt, v))
}

// LastAttemptAt applies equality check predicate on the "last_attempt_at" field. It's identical to LastAttemptAtEQ.
func LastAttemptAt(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldLastAttemptAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldLastError, v))
}

// SucceededAt applies equality check predicate on the "succeeded_at" field. It's identical to SucceededAtEQ.
func SucceededAt(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldSucceededAt, v))
}

// FailedAt applies equality check predicate on the "failed_at" field. It's identical to FailedAtEQ.
func FailedAt(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldFailedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldUpdatedAt, v))
}

// RefundNoEQ applies the EQ predicate on the "refund_no" field.
func RefundNoEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldRefundNo, v))
}

// RefundNoNEQ applies the NEQ predicate on the "refund_no" field.
func RefundNoNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldRefundNo, v))
}

// RefundNoIn applies the In predicate on the "refund_no" field.
func RefundNoIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldRefundNo, vs...))
}

// RefundNoNotIn applies the NotIn predicate on the "refund_no" field.
func RefundNoNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldRefundNo, vs...))
}

// RefundNoGT applies the GT predicate on the "refund_no" field.
func RefundNoGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldRefundNo, v))
}

// RefundNoGTE applies the GTE predicate on the "refund_no" field.
func RefundNoGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldRefundNo, v))
}

// RefundNoLT applies the LT predicate on the "refund_no" field.
func RefundNoLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldRefundNo, v))
}

// RefundNoLTE applies the LTE predicate on the "refund_no" field.
func RefundNoLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldRefundNo, v))
}

// RefundNoContains applies the Contains predicate on the "refund_no" field.
func RefundNoContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldRefundNo, v))
}

// RefundNoHasPrefix applies the HasPrefix predicate on the "refund_no" field.
func RefundNoHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldRefundNo, v))
}

// RefundNoHasSuffix applies the HasSuffix predicate on the "refund_no" field.
func RefundNoHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldRefundNo, v))
}

// RefundNoEqualFold applies the EqualFold predicate on the "refund_no" field.
func RefundNoEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldRefundNo, v))
}

// RefundNoContainsFold applies the ContainsFold predicate on the "refund_no" field.
func RefundNoContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldRefundNo, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldAppID, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldPaymentOrderID, v))
}

// GatewayOrderNoEQ applies the EQ predicate on the "gateway_order_no" field.
func GatewayOrderNoEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldGatewayOrderNo, v))
}

// GatewayOrderNoNEQ applies the NEQ predicate on the "gateway_order_no" field.
func GatewayOrderNoNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldGatewayOrderNo, v))
}

// GatewayOrderNoIn applies the In predicate on the "gateway_order_no" field.
func GatewayOrderNoIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldGatewayOrderNo, vs...))
}

// GatewayOrderNoNotIn applies the NotIn predicate on the "gateway_order_no" field.
func GatewayOrderNoNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldGatewayOrderNo, vs...))
}

// GatewayOrderNoGT applies the GT predicate on the "gateway_order_no" field.
func GatewayOrderNoGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldGatewayOrderNo, v))
}

// GatewayOrderNoGTE applies the GTE predicate on the "gateway_order_no" field.
func GatewayOrderNoGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldGatewayOrderNo, v))
}

// GatewayOrderNoLT applies the LT predicate on the "gateway_order_no" field.
func GatewayOrderNoLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldGatewayOrderNo, v))
}

// GatewayOrderNoLTE applies the LTE predicate on the "gateway_order_no" field.
func GatewayOrderNoLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldGatewayOrderNo, v))
}

// GatewayOrderNoContains applies the Contains predicate on the "gateway_order_no" field.
func GatewayOrderNoContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldGatewayOrderNo, v))
}

// GatewayOrderNoHasPrefix applies the HasPrefix predicate on the "gateway_order_no" field.
func GatewayOrderNoHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldGatewayOrderNo, v))
}

// GatewayOrderNoHasSuffix applies the HasSuffix predicate on the "gateway_order_no" field.
func GatewayOrderNoHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldGatewayOrderNo, v))
}

// GatewayOrderNoEqualFold applies the EqualFold predicate on the "gateway_order_no" field.
func GatewayOrderNoEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldGatewayOrderNo, v))
}

// GatewayOrderNoContainsFold applies the ContainsFold predicate on the "gateway_order_no" field.
func GatewayOrderNoContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldGatewayOrderNo, v))
}

// MerchantOrderNoEQ applies the EQ predicate on the "merchant_order_no" field.
func MerchantOrderNoEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldMerchantOrderNo, v))
}

// MerchantOrderNoNEQ applies the NEQ predicate on the "merchant_order_no" field.
func MerchantOrderNoNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldMerchantOrderNo, v))
}

// MerchantOrderNoIn applies the In predicate on the "merchant_order_no" field.
func MerchantOrderNoIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldMerchantOrderNo, vs...))
}

// MerchantOrderNoNotIn applies the NotIn predicate on the "merchant_order_no" field.
func MerchantOrderNoNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldMerchantOrderNo, vs...))
}

// MerchantOrderNoGT applies the GT predicate on the "merchant_order_no" field.
func MerchantOrderNoGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldMerchantOrderNo, v))
}

// MerchantOrderNoGTE applies the GTE predicate on the "merchant_order_no" field.
func MerchantOrderNoGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldMerchantOrderNo, v))
}

// MerchantOrderNoLT applies the LT predicate on the "merchant_order_no" field.
func MerchantOrderNoLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldMerchantOrderNo, v))
}

// MerchantOrderNoLTE applies the LTE predicate on the "merchant_order_no" field.
func MerchantOrderNoLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldMerchantOrderNo, v))
}

// MerchantOrderNoContains applies the Contains predicate on the "merchant_order_no" field.
func MerchantOrderNoContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldMerchantOrderNo, v))
}

// MerchantOrderNoHasPrefix applies the HasPrefix predicate on the "merchant_order_no" field.
func MerchantOrderNoHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldMerchantOrderNo, v))
}

// MerchantOrderNoHasSuffix applies the HasSuffix predicate on the "merchant_order_no" field.
func MerchantOrderNoHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldMerchantOrderNo, v))
}

// MerchantOrderNoEqualFold applies the EqualFold predicate on the "merchant_order_no" field.
func MerchantOrderNoEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldMerchantOrderNo, v))
}

// MerchantOrderNoContainsFold applies the ContainsFold predicate on the "merchant_order_no" field.
func MerchantOrderNoContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldMerchantOrderNo, v))
}

// MerchantRefundNoEQ applies the EQ predicate on the "merchant_refund_no" field.
func MerchantRefundNoEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldMerchantRefundNo, v))
}

// MerchantRefundNoNEQ applies the NEQ predicate on the "merchant_refund_no" field.
func MerchantRefundNoNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldMerchantRefundNo, v))
}

// MerchantRefundNoIn applies the In predicate on the "merchant_refund_no" field.
func MerchantRefundNoIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldMerchantRefundNo, vs...))
}

// MerchantRefundNoNotIn applies the NotIn predicate on the "merchant_refund_no" field.
func MerchantRefundNoNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldMerchantRefundNo, vs...))
}

// MerchantRefundNoGT applies the GT predicate on the "merchant_refund_no" field.
func MerchantRefundNoGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldMerchantRefundNo, v))
}

// MerchantRefundNoGTE applies the GTE predicate on the "merchant_refund_no" field.
func MerchantRefundNoGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldMerchantRefundNo, v))
}

// MerchantRefundNoLT applies the LT predicate on the "merchant_refund_no" field.
func MerchantRefundNoLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldMerchantRefundNo, v))
}

// MerchantRefundNoLTE applies the LTE predicate on the "merchant_refund_no" field.
func MerchantRefundNoLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldMerchantRefundNo, v))
}

// MerchantRefundNoContains applies the Contains predicate on the "merchant_refund_no" field.
func MerchantRefundNoContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldMerchantRefundNo, v))
}

// MerchantRefundNoHasPrefix applies the HasPrefix predicate on the "merchant_refund_no" field.
func MerchantRefundNoHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldMerchantRefundNo, v))
}

// MerchantRefundNoHasSuffix applies the HasSuffix predicate on the "merchant_refund_no" field.
func MerchantRefundNoHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldMerchantRefundNo, v))
}

// MerchantRefundNoEqualFold applies the EqualFold predicate on the "merchant_refund_no" field.
func MerchantRefundNoEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldMerchantRefundNo, v))
}

// MerchantRefundNoContainsFold applies the ContainsFold predicate on the "merchant_refund_no" field.
func MerchantRefundNoContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldMerchantRefundNo, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldChannel, v))
}

// ChannelAccountIDEQ applies the EQ predicate on the "channel_account_id" field.
func ChannelAccountIDEQ(v int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannelAccountID, v))
}

// ChannelAccountIDNEQ applies the NEQ predicate on the "channel_account_id" field.
func ChannelAccountIDNEQ(v int) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldChannelAccountID, v))
}

// ChannelAccountIDIn applies the In predicate on the "channel_account_id" field.
func ChannelAccountIDIn(vs ...int) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldChannelAccountID, vs...))
}

// ChannelAccountIDNotIn applies the NotIn predicate on the "channel_account_id" field.
func ChannelAccountIDNotIn(vs ...int) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldChannelAccountID, vs...))
}

// ChannelAccountIDGT applies the GT predicate on the "channel_account_id" field.
func ChannelAccountIDGT(v int) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldChannelAccountID, v))
}

// ChannelAccountIDGTE applies the GTE predicate on the "channel_account_id" field.
func ChannelAccountIDGTE(v int) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldChannelAccountID, v))
}

// ChannelAccountIDLT applies the LT predicate on the "channel_account_id" field.
func ChannelAccountIDLT(v int) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldChannelAccountID, v))
}

// ChannelAccountIDLTE applies the LTE predicate on the "channel_account_id" field.
func ChannelAccountIDLTE(v int) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldChannelAccountID, v))
}

// ProviderOrderNoEQ applies the EQ predicate on the "provider_order_no" field.
func ProviderOrderNoEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldProviderOrderNo, v))
}

// ProviderOrderNoNEQ applies the NEQ predicate on the "provider_order_no" field.
func ProviderOrderNoNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldProviderOrderNo, v))
}

// ProviderOrderNoIn applies the In predicate on the "provider_order_no" field.
func ProviderOrderNoIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldProviderOrderNo, vs...))
}

// ProviderOrderNoNotIn applies the NotIn predicate on the "provider_order_no" field.
func ProviderOrderNoNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldProviderOrderNo, vs...))
}

// ProviderOrderNoGT applies the GT predicate on the "provider_order_no" field.
func ProviderOrderNoGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldProviderOrderNo, v))
}

// ProviderOrderNoGTE applies the GTE predicate on the "provider_order_no" field.
func ProviderOrderNoGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldProviderOrderNo, v))
}

// ProviderOrderNoLT applies the LT predicate on the "provider_order_no" field.
func ProviderOrderNoLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldProviderOrderNo, v))
}

// ProviderOrderNoLTE applies the LTE predicate on the "provider_order_no" field.
func ProviderOrderNoLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldProviderOrderNo, v))
}

// ProviderOrderNoContains applies the Contains predicate on the "provider_order_no" field.
func ProviderOrderNoContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldProviderOrderNo, v))
}

// ProviderOrderNoHasPrefix applies the HasPrefix predicate on the "provider_order_no" field.
func ProviderOrderNoHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldProviderOrderNo, v))
}

// ProviderOrderNoHasSuffix applies the HasSuffix predicate on the "provider_order_no" field.
func ProviderOrderNoHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldProviderOrderNo, v))
}

// ProviderOrderNoIsNil applies the IsNil predicate on the "provider_order_no" field.
func ProviderOrderNoIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldProviderOrderNo))
}

// ProviderOrderNoNotNil applies the NotNil predicate on the "provider_order_no" field.
func ProviderOrderNoNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldProviderOrderNo))
}

// ProviderOrderNoEqualFold applies the EqualFold predicate on the "provider_order_no" field.
func ProviderOrderNoEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldProviderOrderNo, v))
}

// ProviderOrderNoContainsFold applies the ContainsFold predicate on the "provider_order_no" field.
func ProviderOrderNoContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldProviderOrderNo, v))
}

// ChannelTradeNoEQ applies the EQ predicate on the "channel_trade_no" field.
func ChannelTradeNoEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannelTradeNo, v))
}

// ChannelTradeNoNEQ applies the NEQ predicate on the "channel_trade_no" field.
func ChannelTradeNoNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldChannelTradeNo, v))
}

// ChannelTradeNoIn applies the In predicate on the "channel_trade_no" field.
func ChannelTradeNoIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldChannelTradeNo, vs...))
}

// ChannelTradeNoNotIn applies the NotIn predicate on the "channel_trade_no" field.
func ChannelTradeNoNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldChannelTradeNo, vs...))
}

// ChannelTradeNoGT applies the GT predicate on the "channel_trade_no" field.
func ChannelTradeNoGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldChannelTradeNo, v))
}

// ChannelTradeNoGTE applies the GTE predicate on the "channel_trade_no" field.
func ChannelTradeNoGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldChannelTradeNo, v))
}

// ChannelTradeNoLT applies the LT predicate on the "channel_trade_no" field.
func ChannelTradeNoLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldChannelTradeNo, v))
}

// ChannelTradeNoLTE applies the LTE predicate on the "channel_trade_no" field.
func ChannelTradeNoLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldChannelTradeNo, v))
}

// ChannelTradeNoContains applies the Contains predicate on the "channel_trade_no" field.
func ChannelTradeNoContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldChannelTradeNo, v))
}

// ChannelTradeNoHasPrefix applies the HasPrefix predicate on the "channel_trade_no" field.
func ChannelTradeNoHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldChannelTradeNo, v))
}

// ChannelTradeNoHasSuffix applies the HasSuffix predicate on the "channel_trade_no" field.
func ChannelTradeNoHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldChannelTradeNo, v))
}

// ChannelTradeNoEqualFold applies the EqualFold predicate on the "channel_trade_no" field.
func ChannelTradeNoEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldChannelTradeNo, v))
}

// ChannelTradeNoContainsFold applies the ContainsFold predicate on the "channel_trade_no" field.
func ChannelTradeNoContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldChannelTradeNo, v))
}

// ChannelRefundNoEQ applies the EQ predicate on the "channel_refund_no" field.
func ChannelRefundNoEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldChannelRefundNo, v))
}

// ChannelRefundNoNEQ applies the NEQ predicate on the "channel_refund_no" field.
func ChannelRefundNoNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldChannelRefundNo, v))
}

// ChannelRefundNoIn applies the In predicate on the "channel_refund_no" field.
func ChannelRefundNoIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldChannelRefundNo, vs...))
}

// ChannelRefundNoNotIn applies the NotIn predicate on the "channel_refund_no" field.
func ChannelRefundNoNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldChannelRefundNo, vs...))
}

// ChannelRefundNoGT applies the GT predicate on the "channel_refund_no" field.
func ChannelRefundNoGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldChannelRefundNo, v))
}

// ChannelRefundNoGTE applies the GTE predicate on the "channel_refund_no" field.
func ChannelRefundNoGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldChannelRefundNo, v))
}

// ChannelRefundNoLT applies the LT predicate on the "channel_refund_no" field.
func ChannelRefundNoLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldChannelRefundNo, v))
}

// ChannelRefundNoLTE applies the LTE predicate on the "channel_refund_no" field.
func ChannelRefundNoLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldChannelRefundNo, v))
}

// ChannelRefundNoContains applies the Contains predicate on the "channel_refund_no" field.
func ChannelRefundNoContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldChannelRefundNo, v))
}

// ChannelRefundNoHasPrefix applies the HasPrefix predicate on the "channel_refund_no" field.
func ChannelRefundNoHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldChannelRefundNo, v))
}

// ChannelRefundNoHasSuffix applies the HasSuffix predicate on the "channel_refund_no" field.
func ChannelRefundNoHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldChannelRefundNo, v))
}

// ChannelRefundNoIsNil applies the IsNil predicate on the "channel_refund_no" field.
func ChannelRefundNoIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldChannelRefundNo))
}

// ChannelRefundNoNotNil applies the NotNil predicate on the "channel_refund_no" field.
func ChannelRefundNoNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldChannelRefundNo))
}

// ChannelRefundNoEqualFold applies the EqualFold predicate on the "channel_refund_no" field.
func ChannelRefundNoEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldChannelRefundNo, v))
}

// ChannelRefundNoContainsFold applies the ContainsFold predicate on the "channel_refund_no" field.
func ChannelRefundNoContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldChannelRefundNo, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldCurrency, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldStatus, v))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldFailureReason, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldMetadata))
}

// ProviderSnapshotIsNil applies the IsNil predicate on the "provider_snapshot" field.
func ProviderSnapshotIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldProviderSnapshot))
}

// ProviderSnapshotNotNil applies the NotNil predicate on the "provider_snapshot" field.
func ProviderSnapshotNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldProviderSnapshot))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldAttemptCount, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldNextAttemptAt, v))
}

// NextAttemptAtIsNil applies the IsNil predicate on the "next_attempt_at" field.
func NextAttemptAtIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldNextAttemptAt))
}

// NextAttemptAtNotNil applies the NotNil predicate on the "next_attempt_at" field.
func NextAttemptAtNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldNextAttemptAt))
}

// LastAttemptAtEQ applies the EQ predicate on the "last_attempt_at" field.
func LastAttemptAtEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldLastAttemptAt, v))
}

// LastAttemptAtNEQ applies the NEQ predicate on the "last_attempt_at" field.
func LastAttemptAtNEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldLastAttemptAt, v))
}

// LastAttemptAtIn applies the In predicate on the "last_attempt_at" field.
func LastAttemptAtIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldLastAttemptAt, vs...))
}

// LastAttemptAtNotIn applies the NotIn predicate on the "last_attempt_at" field.
func LastAttemptAtNotIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldLastAttemptAt, vs...))
}

// LastAttemptAtGT applies the GT predicate on the "last_attempt_at" field.
func LastAttemptAtGT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldLastAttemptAt, v))
}

// LastAttemptAtGTE applies the GTE predicate on the "last_attempt_at" field.
func LastAttemptAtGTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldLastAttemptAt, v))
}

// LastAttemptAtLT applies the LT predicate on the "last_attempt_at" field.
func LastAttemptAtLT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldLastAttemptAt, v))
}

// LastAttemptAtLTE applies the LTE predicate on the "last_attempt_at" field.
func LastAttemptAtLTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldLastAttemptAt, v))
}

// LastAttemptAtIsNil applies the IsNil predicate on the "last_attempt_at" field.
func LastAttemptAtIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldLastAttemptAt))
}

// LastAttemptAtNotNil applies the NotNil predicate on the "last_attempt_at" field.
func LastAttemptAtNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldLastAttemptAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.Refund {
	return predicate.Refund(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.Refund {
	return predicate.Refund(sql.FieldContainsFold(FieldLastError, v))
}

// SucceededAtEQ applies the EQ predicate on the "succeeded_at" field.
func SucceededAtEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldSucceededAt, v))
}

// SucceededAtNEQ applies the NEQ predicate on the "succeeded_at" field.
func SucceededAtNEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldSucceededAt, v))
}

// SucceededAtIn applies the In predicate on the "succeeded_at" field.
func SucceededAtIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldSucceededAt, vs...))
}

// SucceededAtNotIn applies the NotIn predicate on the "succeeded_at" field.
func SucceededAtNotIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldSucceededAt, vs...))
}

// SucceededAtGT applies the GT predicate on the "succeeded_at" field.
func SucceededAtGT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldSucceededAt, v))
}

// SucceededAtGTE applies the GTE predicate on the "succeeded_at" field.
func SucceededAtGTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldSucceededAt, v))
}

// SucceededAtLT applies the LT predicate on the "succeeded_at" field.
func SucceededAtLT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldSucceededAt, v))
}

// SucceededAtLTE applies the LTE predicate on the "succeeded_at" field.
func SucceededAtLTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldSucceededAt, v))
}

// SucceededAtIsNil applies the IsNil predicate on the "succeeded_at" field.
func SucceededAtIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldSucceededAt))
}

// SucceededAtNotNil applies the NotNil predicate on the "succeeded_at" field.
func SucceededAtNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldSucceededAt))
}

// FailedAtEQ applies the EQ predicate on the "failed_at" field.
func FailedAtEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldFailedAt, v))
}

// FailedAtNEQ applies the NEQ predicate on the "failed_at" field.
func FailedAtNEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldFailedAt, v))
}

// FailedAtIn applies the In predicate on the "failed_at" field.
func FailedAtIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldFailedAt, vs...))
}

// FailedAtNotIn applies the NotIn predicate on the "failed_at" field.
func FailedAtNotIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldFailedAt, vs...))
}

// FailedAtGT applies the GT predicate on the "failed_at" field.
func FailedAtGT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldFailedAt, v))
}

// FailedAtGTE applies the GTE predicate on the "failed_at" field.
func FailedAtGTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldFailedAt, v))
}

// FailedAtLT applies the LT predicate on the "failed_at" field.
func FailedAtLT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldFailedAt, v))
}

// FailedAtLTE applies the LTE predicate on the "failed_at" field.
func FailedAtLTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldFailedAt, v))
}

// FailedAtIsNil applies the IsNil predicate on the "failed_at" field.
func FailedAtIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldFailedAt))
}

// FailedAtNotNil applies the NotNil predicate on the "failed_at" field.
func FailedAtNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldFailedAt))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.Refund {
	return predicate.Refund(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.Refund {
	return predicate.Refund(sql.FieldNotNull(FieldClosedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Refund {
	return predicate.Refund(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Refund) predicate.Refund {
	return predicate.Refund(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Refund) predicate.Refund {
	return predicate.Refund(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Refund) predicate.Refund {
	return predicate.Refund(sql.NotPredicates(p))
}
