// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"payment-gateway/ent/channelaccount"
	"payment-gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChannelAccountUpdate is the builder for updating ChannelAccount entities.
type ChannelAccountUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelAccountMutation
}

// Where appends a list predicates to the ChannelAccountUpdate builder.
func (_u *ChannelAccountUpdate) Where(ps ...predicate.ChannelAccount) *ChannelAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannel sets the "channel" field.
func (_u *ChannelAccountUpdate) SetChannel(v string) *ChannelAccountUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableChannel(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelAccountUpdate) SetName(v string) *ChannelAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableName(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelAccountUpdate) SetEnabled(v bool) *ChannelAccountUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableEnabled(v *bool) *ChannelAccountUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEnv sets the "env" field.
func (_u *ChannelAccountUpdate) SetEnv(v string) *ChannelAccountUpdate {
	_u.mutation.SetEnv(v)
	return _u
}

// SetNillableEnv sets the "env" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableEnv(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetEnv(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ChannelAccountUpdate) SetConfig(v map[string]interface{}) *ChannelAccountUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ChannelAccountUpdate) ClearConfig() *ChannelAccountUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelAccountUpdate) SetUpdatedAt(v time.Time) *ChannelAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChannelAccountMutation object of the builder.
func (_u *ChannelAccountUpdate) Mutation() *ChannelAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ChannelAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(channelaccount.Table, channelaccount.Columns, sqlgraph.NewFieldSpec(channelaccount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(channelaccount.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channelaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(channelaccount.FieldEnv, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(channelaccount.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(channelaccount.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelAccountUpdateOne is the builder for updating a single ChannelAccount entity.
type ChannelAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelAccountMutation
}

// SetChannel sets the "channel" field.
func (_u *ChannelAccountUpdateOne) SetChannel(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableChannel(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelAccountUpdateOne) SetName(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableName(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelAccountUpdateOne) SetEnabled(v bool) *ChannelAccountUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableEnabled(v *bool) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEnv sets the "env" field.
func (_u *ChannelAccountUpdateOne) SetEnv(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetEnv(v)
	return _u
}

// SetNillableEnv sets the "env" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableEnv(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetEnv(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ChannelAccountUpdateOne) SetConfig(v map[string]interface{}) *ChannelAccountUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ChannelAccountUpdateOne) ClearConfig() *ChannelAccountUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelAccountUpdateOne) SetUpdatedAt(v time.Time) *ChannelAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChannelAccountMutation object of the builder.
func (_u *ChannelAccountUpdateOne) Mutation() *ChannelAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelAccountUpdate builder.
func (_u *ChannelAccountUpdateOne) Where(ps ...predicate.ChannelAccount) *ChannelAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelAccountUpdateOne) Select(field string, fields ...string) *ChannelAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelAccount entity.
func (_u *ChannelAccountUpdateOne) Save(ctx context.Context) (*ChannelAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelAccountUpdateOne) SaveX(ctx context.Context) *ChannelAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ChannelAccountUpdateOne) sqlSave(ctx context.Context) (_node *ChannelAccount, err error) {
	_spec := sqlgraph.NewUpdateSpec(channelaccount.Table, channelaccount.Columns, sqlgraph.NewFieldSpec(channelaccount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelaccount.FieldID)
		for _, f := range fields {
			if !channelaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(channelaccount.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channelaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(channelaccount.FieldEnv, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(channelaccount.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(channelaccount.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ChannelAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
