// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"payment-gateway/ent/gatewayconfig"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GatewayConfig is the model entity for the GatewayConfig schema.
type GatewayConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SiteName holds the value of the "site_name" field.
	SiteName string `json:"site_name,omitempty"`
	// GatewayBaseURL holds the value of the "gateway_base_url" field.
	GatewayBaseURL string `json:"gateway_base_url,omitempty"`
	// PaymentNotifyPath holds the value of the "payment_notify_path" field.
	PaymentNotifyPath string `json:"payment_notify_path,omitempty"`
	// DefaultCurrency holds the value of the "default_currency" field.
	DefaultCurrency string `json:"default_currency,omitempty"`
	// DefaultLocale holds the value of the "default_locale" field.
	DefaultLocale string `json:"default_locale,omitempty"`
	// RequestIDEnabled holds the value of the "request_id_enabled" field.
	RequestIDEnabled bool `json:"request_id_enabled,omitempty"`
	// MaintenanceMode holds the value of the "maintenance_mode" field.
	MaintenanceMode bool `json:"maintenance_mode,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra map[string]interface{} `json:"extra,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GatewayConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gatewayconfig.FieldExtra:
			values[i] = new([]byte)
		case gatewayconfig.FieldRequestIDEnabled, gatewayconfig.FieldMaintenanceMode:
			values[i] = new(sql.NullBool)
		case gatewayconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case gatewayconfig.FieldSiteName, gatewayconfig.FieldGatewayBaseURL, gatewayconfig.FieldPaymentNotifyPath, gatewayconfig.FieldDefaultCurrency, gatewayconfig.FieldDefaultLocale:
			values[i] = new(sql.NullString)
		case gatewayconfig.FieldCreatedAt, gatewayconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GatewayConfig fields.
func (_m *GatewayConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gatewayconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gatewayconfig.FieldSiteName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_name", values[i])
			} else if value.Valid {
				_m.SiteName = value.String
			}
		case gatewayconfig.FieldGatewayBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_base_url", values[i])
			} else if value.Valid {
				_m.GatewayBaseURL = value.String
			}
		case gatewayconfig.FieldPaymentNotifyPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_notify_path", values[i])
			} else if value.Valid {
				_m.PaymentNotifyPath = value.String
			}
		case gatewayconfig.FieldDefaultCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_currency", values[i])
			} else if value.Valid {
				_m.DefaultCurrency = value.String
			}
		case gatewayconfig.FieldDefaultLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_locale", values[i])
			} else if value.Valid {
				_m.DefaultLocale = value.String
			}
		case gatewayconfig.FieldRequestIDEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field request_id_enabled", values[i])
			} else if value.Valid {
				_m.RequestIDEnabled = value.Bool
			}
		case gatewayconfig.FieldMaintenanceMode:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field maintenance_mode", values[i])
			} else if value.Valid {
				_m.MaintenanceMode = value.Bool
			}
		case gatewayconfig.FieldExtra:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Extra); err != nil {
					return fmt.Errorf("unmarshal field extra: %w", err)
				}
			}
		case gatewayconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gatewayconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GatewayConfig.
// This includes values selected through modifiers, order, etc.
func (_m *GatewayConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GatewayConfig.
// Note that you need to call GatewayConfig.Unwrap() before calling this method if this GatewayConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GatewayConfig) Update() *GatewayConfigUpdateOne {
	return NewGatewayConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GatewayConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GatewayConfig) Unwrap() *GatewayConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GatewayConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GatewayConfig) String() string {
	var builder strings.Builder
	builder.WriteString("GatewayConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("site_name=")
	builder.WriteString(_m.SiteName)
	builder.WriteString(", ")
	builder.WriteString("gateway_base_url=")
	builder.WriteString(_m.GatewayBaseURL)
	builder.WriteString(", ")
	builder.WriteString("payment_notify_path=")
	builder.WriteString(_m.PaymentNotifyPath)
	builder.WriteString(", ")
	builder.WriteString("default_currency=")
	builder.WriteString(_m.DefaultCurrency)
	builder.WriteString(", ")
	builder.WriteString("default_locale=")
	builder.WriteString(_m.DefaultLocale)
	builder.WriteString(", ")
	builder.WriteString("request_id_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestIDEnabled))
	builder.WriteString(", ")
	builder.WriteString("maintenance_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaintenanceMode))
	builder.WriteString(", ")
	builder.WriteString("extra=")
	builder.WriteString(fmt.Sprintf("%v", _m.Extra))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GatewayConfigs is a parsable slice of GatewayConfig.
type GatewayConfigs []*GatewayConfig
