// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"payment-gateway/ent/paymentorder"
	"payment-gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_u *PaymentOrderUpdate) SetGatewayOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetGatewayOrderNo(v)
	return _u
}

// SetNillableGatewayOrderNo sets the "gateway_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableGatewayOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetGatewayOrderNo(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *PaymentOrderUpdate) SetAppID(v string) *PaymentOrderUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAppID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetMerchantOrderNo sets the "merchant_order_no" field.
func (_u *PaymentOrderUpdate) SetMerchantOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetMerchantOrderNo(v)
	return _u
}

// SetNillableMerchantOrderNo sets the "merchant_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableMerchantOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetMerchantOrderNo(*v)
	}
	return _u
}

// SetBusinessType sets the "business_type" field.
func (_u *PaymentOrderUpdate) SetBusinessType(v string) *PaymentOrderUpdate {
	_u.mutation.SetBusinessType(v)
	return _u
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableBusinessType(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetBusinessType(*v)
	}
	return _u
}

// ClearBusinessType clears the value of the "business_type" field.
func (_u *PaymentOrderUpdate) ClearBusinessType() *PaymentOrderUpdate {
	_u.mutation.ClearBusinessType()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *PaymentOrderUpdate) SetSubject(v string) *PaymentOrderUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableSubject(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentOrderUpdate) SetDescription(v string) *PaymentOrderUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableDescription(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentOrderUpdate) ClearDescription() *PaymentOrderUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdate) SetAmount(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmount(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdate) AddAmount(v int64) *PaymentOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentOrderUpdate) SetCurrency(v string) *PaymentOrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCurrency(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetSettlementAmount sets the "settlement_amount" field.
func (_u *PaymentOrderUpdate) SetSettlementAmount(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetSettlementAmount()
	_u.mutation.SetSettlementAmount(v)
	return _u
}

// SetNillableSettlementAmount sets the "settlement_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableSettlementAmount(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetSettlementAmount(*v)
	}
	return _u
}

// AddSettlementAmount adds value to the "settlement_amount" field.
func (_u *PaymentOrderUpdate) AddSettlementAmount(v int64) *PaymentOrderUpdate {
	_u.mutation.AddSettlementAmount(v)
	return _u
}

// ClearSettlementAmount clears the value of the "settlement_amount" field.
func (_u *PaymentOrderUpdate) ClearSettlementAmount() *PaymentOrderUpdate {
	_u.mutation.ClearSettlementAmount()
	return _u
}

// SetSettlementCurrency sets the "settlement_currency" field.
func (_u *PaymentOrderUpdate) SetSettlementCurrency(v string) *PaymentOrderUpdate {
	_u.mutation.SetSettlementCurrency(v)
	return _u
}

// SetNillableSettlementCurrency sets the "settlement_currency" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableSettlementCurrency(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetSettlementCurrency(*v)
	}
	return _u
}

// ClearSettlementCurrency clears the value of the "settlement_currency" field.
func (_u *PaymentOrderUpdate) ClearSettlementCurrency() *PaymentOrderUpdate {
	_u.mutation.ClearSettlementCurrency()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PaymentOrderUpdate) SetChannel(v string) *PaymentOrderUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableChannel(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// ClearChannel clears the value of the "channel" field.
func (_u *PaymentOrderUpdate) ClearChannel() *PaymentOrderUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// SetChannelAccountID sets the "channel_account_id" field.
func (_u *PaymentOrderUpdate) SetChannelAccountID(v int) *PaymentOrderUpdate {
	_u.mutation.ResetChannelAccountID()
	_u.mutation.SetChannelAccountID(v)
	return _u
}

// SetNillableChannelAccountID sets the "channel_account_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableChannelAccountID(v *int) *PaymentOrderUpdate {
	if v != nil {
		_u.SetChannelAccountID(*v)
	}
	return _u
}

// AddChannelAccountID adds value to the "channel_account_id" field.
func (_u *PaymentOrderUpdate) AddChannelAccountID(v int) *PaymentOrderUpdate {
	_u.mutation.AddChannelAccountID(v)
	return _u
}

// ClearChannelAccountID clears the value of the "channel_account_id" field.
func (_u *PaymentOrderUpdate) ClearChannelAccountID() *PaymentOrderUpdate {
	_u.mutation.ClearChannelAccountID()
	return _u
}

// SetPayMethod sets the "pay_method" field.
func (_u *PaymentOrderUpdate) SetPayMethod(v string) *PaymentOrderUpdate {
	_u.mutation.SetPayMethod(v)
	return _u
}

// SetNillablePayMethod sets the "pay_method" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePayMethod(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPayMethod(*v)
	}
	return _u
}

// ClearPayMethod clears the value of the "pay_method" field.
func (_u *PaymentOrderUpdate) ClearPayMethod() *PaymentOrderUpdate {
	_u.mutation.ClearPayMethod()
	return _u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_u *PaymentOrderUpdate) SetProviderOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetProviderOrderNo(v)
	return _u
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProviderOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProviderOrderNo(*v)
	}
	return _u
}

// ClearProviderOrderNo clears the value of the "provider_order_no" field.
func (_u *PaymentOrderUpdate) ClearProviderOrderNo() *PaymentOrderUpdate {
	_u.mutation.ClearProviderOrderNo()
	return _u
}

// SetChannelTradeNo sets the "channel_trade_no" field.
func (_u *PaymentOrderUpdate) SetChannelTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetChannelTradeNo(v)
	return _u
}

// SetNillableChannelTradeNo sets the "channel_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableChannelTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetChannelTradeNo(*v)
	}
	return _u
}

// ClearChannelTradeNo clears the value of the "channel_trade_no" field.
func (_u *PaymentOrderUpdate) ClearChannelTradeNo() *PaymentOrderUpdate {
	_u.mutation.ClearChannelTradeNo()
	return _u
}

// SetReturnURL sets the "return_url" field.
func (_u *PaymentOrderUpdate) SetReturnURL(v string) *PaymentOrderUpdate {
	_u.mutation.SetReturnURL(v)
	return _u
}

// SetNillableReturnURL sets the "return_url" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableReturnURL(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetReturnURL(*v)
	}
	return _u
}

// ClearReturnURL clears the value of the "return_url" field.
func (_u *PaymentOrderUpdate) ClearReturnURL() *PaymentOrderUpdate {
	_u.mutation.ClearReturnURL()
	return _u
}

// SetCheckoutTokenHash sets the "checkout_token_hash" field.
func (_u *PaymentOrderUpdate) SetCheckoutTokenHash(v string) *PaymentOrderUpdate {
	_u.mutation.SetCheckoutTokenHash(v)
	return _u
}

// SetNillableCheckoutTokenHash sets the "checkout_token_hash" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCheckoutTokenHash(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCheckoutTokenHash(*v)
	}
	return _u
}

// ClearCheckoutTokenHash clears the value of the "checkout_token_hash" field.
func (_u *PaymentOrderUpdate) ClearCheckoutTokenHash() *PaymentOrderUpdate {
	_u.mutation.ClearCheckoutTokenHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PaymentOrderUpdate) SetExpiresAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableExpiresAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *PaymentOrderUpdate) ClearExpiresAt() *PaymentOrderUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *PaymentOrderUpdate) SetFailedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableFailedAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *PaymentOrderUpdate) ClearFailedAt() *PaymentOrderUpdate {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *PaymentOrderUpdate) SetFailureReason(v string) *PaymentOrderUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableFailureReason(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *PaymentOrderUpdate) ClearFailureReason() *PaymentOrderUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *PaymentOrderUpdate) SetClosedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableClosedAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *PaymentOrderUpdate) ClearClosedAt() *PaymentOrderUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentOrderUpdate) SetMetadata(v map[string]interface{}) *PaymentOrderUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentOrderUpdate) ClearMetadata() *PaymentOrderUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdate) SetUpdatedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GatewayOrderNo(); ok {
		_spec.SetField(paymentorder.FieldGatewayOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(paymentorder.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MerchantOrderNo(); ok {
		_spec.SetField(paymentorder.FieldMerchantOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessType(); ok {
		_spec.SetField(paymentorder.FieldBusinessType, field.TypeString, value)
	}
	if _u.mutation.BusinessTypeCleared() {
		_spec.ClearField(paymentorder.FieldBusinessType, field.TypeString)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(paymentorder.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentorder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentorder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettlementAmount(); ok {
		_spec.SetField(paymentorder.FieldSettlementAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettlementAmount(); ok {
		_spec.AddField(paymentorder.FieldSettlementAmount, field.TypeInt64, value)
	}
	if _u.mutation.SettlementAmountCleared() {
		_spec.ClearField(paymentorder.FieldSettlementAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.SettlementCurrency(); ok {
		_spec.SetField(paymentorder.FieldSettlementCurrency, field.TypeString, value)
	}
	if _u.mutation.SettlementCurrencyCleared() {
		_spec.ClearField(paymentorder.FieldSettlementCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(paymentorder.FieldChannel, field.TypeString, value)
	}
	if _u.mutation.ChannelCleared() {
		_spec.ClearField(paymentorder.FieldChannel, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelAccountID(); ok {
		_spec.SetField(paymentorder.FieldChannelAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChannelAccountID(); ok {
		_spec.AddField(paymentorder.FieldChannelAccountID, field.TypeInt, value)
	}
	if _u.mutation.ChannelAccountIDCleared() {
		_spec.ClearField(paymentorder.FieldChannelAccountID, field.TypeInt)
	}
	if value, ok := _u.mutation.PayMethod(); ok {
		_spec.SetField(paymentorder.FieldPayMethod, field.TypeString, value)
	}
	if _u.mutation.PayMethodCleared() {
		_spec.ClearField(paymentorder.FieldPayMethod, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderOrderNo(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderNo, field.TypeString, value)
	}
	if _u.mutation.ProviderOrderNoCleared() {
		_spec.ClearField(paymentorder.FieldProviderOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelTradeNo(); ok {
		_spec.SetField(paymentorder.FieldChannelTradeNo, field.TypeString, value)
	}
	if _u.mutation.ChannelTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldChannelTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.ReturnURL(); ok {
		_spec.SetField(paymentorder.FieldReturnURL, field.TypeString, value)
	}
	if _u.mutation.ReturnURLCleared() {
		_spec.ClearField(paymentorder.FieldReturnURL, field.TypeString)
	}
	if value, ok := _u.mutation.CheckoutTokenHash(); ok {
		_spec.SetField(paymentorder.FieldCheckoutTokenHash, field.TypeString, value)
	}
	if _u.mutation.CheckoutTokenHashCleared() {
		_spec.ClearField(paymentorder.FieldCheckoutTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(paymentorder.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(paymentorder.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(paymentorder.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(paymentorder.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(paymentorder.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(paymentorder.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(paymentorder.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentorder.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentorder.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_u *PaymentOrderUpdateOne) SetGatewayOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetGatewayOrderNo(v)
	return _u
}

// SetNillableGatewayOrderNo sets the "gateway_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableGatewayOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetGatewayOrderNo(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *PaymentOrderUpdateOne) SetAppID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAppID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetMerchantOrderNo sets the "merchant_order_no" field.
func (_u *PaymentOrderUpdateOne) SetMerchantOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetMerchantOrderNo(v)
	return _u
}

// SetNillableMerchantOrderNo sets the "merchant_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableMerchantOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetMerchantOrderNo(*v)
	}
	return _u
}

// SetBusinessType sets the "business_type" field.
func (_u *PaymentOrderUpdateOne) SetBusinessType(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetBusinessType(v)
	return _u
}

// SetNillableBusinessType sets the "business_type" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableBusinessType(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetBusinessType(*v)
	}
	return _u
}

// ClearBusinessType clears the value of the "business_type" field.
func (_u *PaymentOrderUpdateOne) ClearBusinessType() *PaymentOrderUpdateOne {
	_u.mutation.ClearBusinessType()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *PaymentOrderUpdateOne) SetSubject(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableSubject(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentOrderUpdateOne) SetDescription(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableDescription(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentOrderUpdateOne) ClearDescription() *PaymentOrderUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdateOne) SetAmount(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmount(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdateOne) AddAmount(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentOrderUpdateOne) SetCurrency(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCurrency(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetSettlementAmount sets the "settlement_amount" field.
func (_u *PaymentOrderUpdateOne) SetSettlementAmount(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetSettlementAmount()
	_u.mutation.SetSettlementAmount(v)
	return _u
}

// SetNillableSettlementAmount sets the "settlement_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableSettlementAmount(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetSettlementAmount(*v)
	}
	return _u
}

// AddSettlementAmount adds value to the "settlement_amount" field.
func (_u *PaymentOrderUpdateOne) AddSettlementAmount(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddSettlementAmount(v)
	return _u
}

// ClearSettlementAmount clears the value of the "settlement_amount" field.
func (_u *PaymentOrderUpdateOne) ClearSettlementAmount() *PaymentOrderUpdateOne {
	_u.mutation.ClearSettlementAmount()
	return _u
}

// SetSettlementCurrency sets the "settlement_currency" field.
func (_u *PaymentOrderUpdateOne) SetSettlementCurrency(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetSettlementCurrency(v)
	return _u
}

// SetNillableSettlementCurrency sets the "settlement_currency" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableSettlementCurrency(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetSettlementCurrency(*v)
	}
	return _u
}

// ClearSettlementCurrency clears the value of the "settlement_currency" field.
func (_u *PaymentOrderUpdateOne) ClearSettlementCurrency() *PaymentOrderUpdateOne {
	_u.mutation.ClearSettlementCurrency()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PaymentOrderUpdateOne) SetChannel(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableChannel(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// ClearChannel clears the value of the "channel" field.
func (_u *PaymentOrderUpdateOne) ClearChannel() *PaymentOrderUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// SetChannelAccountID sets the "channel_account_id" field.
func (_u *PaymentOrderUpdateOne) SetChannelAccountID(v int) *PaymentOrderUpdateOne {
	_u.mutation.ResetChannelAccountID()
	_u.mutation.SetChannelAccountID(v)
	return _u
}

// SetNillableChannelAccountID sets the "channel_account_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableChannelAccountID(v *int) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetChannelAccountID(*v)
	}
	return _u
}

// AddChannelAccountID adds value to the "channel_account_id" field.
func (_u *PaymentOrderUpdateOne) AddChannelAccountID(v int) *PaymentOrderUpdateOne {
	_u.mutation.AddChannelAccountID(v)
	return _u
}

// ClearChannelAccountID clears the value of the "channel_account_id" field.
func (_u *PaymentOrderUpdateOne) ClearChannelAccountID() *PaymentOrderUpdateOne {
	_u.mutation.ClearChannelAccountID()
	return _u
}

// SetPayMethod sets the "pay_method" field.
func (_u *PaymentOrderUpdateOne) SetPayMethod(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetPayMethod(v)
	return _u
}

// SetNillablePayMethod sets the "pay_method" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePayMethod(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPayMethod(*v)
	}
	return _u
}

// ClearPayMethod clears the value of the "pay_method" field.
func (_u *PaymentOrderUpdateOne) ClearPayMethod() *PaymentOrderUpdateOne {
	_u.mutation.ClearPayMethod()
	return _u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_u *PaymentOrderUpdateOne) SetProviderOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProviderOrderNo(v)
	return _u
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProviderOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProviderOrderNo(*v)
	}
	return _u
}

// ClearProviderOrderNo clears the value of the "provider_order_no" field.
func (_u *PaymentOrderUpdateOne) ClearProviderOrderNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearProviderOrderNo()
	return _u
}

// SetChannelTradeNo sets the "channel_trade_no" field.
func (_u *PaymentOrderUpdateOne) SetChannelTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetChannelTradeNo(v)
	return _u
}

// SetNillableChannelTradeNo sets the "channel_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableChannelTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetChannelTradeNo(*v)
	}
	return _u
}

// ClearChannelTradeNo clears the value of the "channel_trade_no" field.
func (_u *PaymentOrderUpdateOne) ClearChannelTradeNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearChannelTradeNo()
	return _u
}

// SetReturnURL sets the "return_url" field.
func (_u *PaymentOrderUpdateOne) SetReturnURL(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetReturnURL(v)
	return _u
}

// SetNillableReturnURL sets the "return_url" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableReturnURL(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetReturnURL(*v)
	}
	return _u
}

// ClearReturnURL clears the value of the "return_url" field.
func (_u *PaymentOrderUpdateOne) ClearReturnURL() *PaymentOrderUpdateOne {
	_u.mutation.ClearReturnURL()
	return _u
}

// SetCheckoutTokenHash sets the "checkout_token_hash" field.
func (_u *PaymentOrderUpdateOne) SetCheckoutTokenHash(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCheckoutTokenHash(v)
	return _u
}

// SetNillableCheckoutTokenHash sets the "checkout_token_hash" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCheckoutTokenHash(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCheckoutTokenHash(*v)
	}
	return _u
}

// ClearCheckoutTokenHash clears the value of the "checkout_token_hash" field.
func (_u *PaymentOrderUpdateOne) ClearCheckoutTokenHash() *PaymentOrderUpdateOne {
	_u.mutation.ClearCheckoutTokenHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PaymentOrderUpdateOne) SetExpiresAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableExpiresAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *PaymentOrderUpdateOne) ClearExpiresAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *PaymentOrderUpdateOne) SetFailedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableFailedAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *PaymentOrderUpdateOne) ClearFailedAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *PaymentOrderUpdateOne) SetFailureReason(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableFailureReason(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *PaymentOrderUpdateOne) ClearFailureReason() *PaymentOrderUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *PaymentOrderUpdateOne) SetClosedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableClosedAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *PaymentOrderUpdateOne) ClearClosedAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentOrderUpdateOne) SetMetadata(v map[string]interface{}) *PaymentOrderUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentOrderUpdateOne) ClearMetadata() *PaymentOrderUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GatewayOrderNo(); ok {
		_spec.SetField(paymentorder.FieldGatewayOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(paymentorder.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MerchantOrderNo(); ok {
		_spec.SetField(paymentorder.FieldMerchantOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessType(); ok {
		_spec.SetField(paymentorder.FieldBusinessType, field.TypeString, value)
	}
	if _u.mutation.BusinessTypeCleared() {
		_spec.ClearField(paymentorder.FieldBusinessType, field.TypeString)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(paymentorder.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentorder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentorder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettlementAmount(); ok {
		_spec.SetField(paymentorder.FieldSettlementAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettlementAmount(); ok {
		_spec.AddField(paymentorder.FieldSettlementAmount, field.TypeInt64, value)
	}
	if _u.mutation.SettlementAmountCleared() {
		_spec.ClearField(paymentorder.FieldSettlementAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.SettlementCurrency(); ok {
		_spec.SetField(paymentorder.FieldSettlementCurrency, field.TypeString, value)
	}
	if _u.mutation.SettlementCurrencyCleared() {
		_spec.ClearField(paymentorder.FieldSettlementCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(paymentorder.FieldChannel, field.TypeString, value)
	}
	if _u.mutation.ChannelCleared() {
		_spec.ClearField(paymentorder.FieldChannel, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelAccountID(); ok {
		_spec.SetField(paymentorder.FieldChannelAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChannelAccountID(); ok {
		_spec.AddField(paymentorder.FieldChannelAccountID, field.TypeInt, value)
	}
	if _u.mutation.ChannelAccountIDCleared() {
		_spec.ClearField(paymentorder.FieldChannelAccountID, field.TypeInt)
	}
	if value, ok := _u.mutation.PayMethod(); ok {
		_spec.SetField(paymentorder.FieldPayMethod, field.TypeString, value)
	}
	if _u.mutation.PayMethodCleared() {
		_spec.ClearField(paymentorder.FieldPayMethod, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderOrderNo(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderNo, field.TypeString, value)
	}
	if _u.mutation.ProviderOrderNoCleared() {
		_spec.ClearField(paymentorder.FieldProviderOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelTradeNo(); ok {
		_spec.SetField(paymentorder.FieldChannelTradeNo, field.TypeString, value)
	}
	if _u.mutation.ChannelTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldChannelTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.ReturnURL(); ok {
		_spec.SetField(paymentorder.FieldReturnURL, field.TypeString, value)
	}
	if _u.mutation.ReturnURLCleared() {
		_spec.ClearField(paymentorder.FieldReturnURL, field.TypeString)
	}
	if value, ok := _u.mutation.CheckoutTokenHash(); ok {
		_spec.SetField(paymentorder.FieldCheckoutTokenHash, field.TypeString, value)
	}
	if _u.mutation.CheckoutTokenHashCleared() {
		_spec.ClearField(paymentorder.FieldCheckoutTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(paymentorder.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(paymentorder.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(paymentorder.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(paymentorder.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(paymentorder.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(paymentorder.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(paymentorder.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentorder.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentorder.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
