// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"payment-gateway/ent/paymentreconciliation"
	"payment-gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentReconciliationUpdate is the builder for updating PaymentReconciliation entities.
type PaymentReconciliationUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentReconciliationMutation
}

// Where appends a list predicates to the PaymentReconciliationUpdate builder.
func (_u *PaymentReconciliationUpdate) Where(ps ...predicate.PaymentReconciliation) *PaymentReconciliationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *PaymentReconciliationUpdate) SetPaymentOrderID(v int) *PaymentReconciliationUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillablePaymentOrderID(v *int) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *PaymentReconciliationUpdate) AddPaymentOrderID(v int) *PaymentReconciliationUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_u *PaymentReconciliationUpdate) SetGatewayOrderNo(v string) *PaymentReconciliationUpdate {
	_u.mutation.SetGatewayOrderNo(v)
	return _u
}

// SetNillableGatewayOrderNo sets the "gateway_order_no" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableGatewayOrderNo(v *string) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetGatewayOrderNo(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PaymentReconciliationUpdate) SetChannel(v string) *PaymentReconciliationUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableChannel(v *string) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetChannelAccountID sets the "channel_account_id" field.
func (_u *PaymentReconciliationUpdate) SetChannelAccountID(v int) *PaymentReconciliationUpdate {
	_u.mutation.ResetChannelAccountID()
	_u.mutation.SetChannelAccountID(v)
	return _u
}

// SetNillableChannelAccountID sets the "channel_account_id" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableChannelAccountID(v *int) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetChannelAccountID(*v)
	}
	return _u
}

// AddChannelAccountID adds value to the "channel_account_id" field.
func (_u *PaymentReconciliationUpdate) AddChannelAccountID(v int) *PaymentReconciliationUpdate {
	_u.mutation.AddChannelAccountID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentReconciliationUpdate) SetStatus(v string) *PaymentReconciliationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableStatus(v *string) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *PaymentReconciliationUpdate) SetAttemptCount(v int) *PaymentReconciliationUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableAttemptCount(v *int) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *PaymentReconciliationUpdate) AddAttemptCount(v int) *PaymentReconciliationUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PaymentReconciliationUpdate) SetNextAttemptAt(v time.Time) *PaymentReconciliationUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableNextAttemptAt(v *time.Time) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PaymentReconciliationUpdate) ClearNextAttemptAt() *PaymentReconciliationUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *PaymentReconciliationUpdate) SetLastAttemptAt(v time.Time) *PaymentReconciliationUpdate {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableLastAttemptAt(v *time.Time) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *PaymentReconciliationUpdate) ClearLastAttemptAt() *PaymentReconciliationUpdate {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetLastProviderStatus sets the "last_provider_status" field.
func (_u *PaymentReconciliationUpdate) SetLastProviderStatus(v string) *PaymentReconciliationUpdate {
	_u.mutation.SetLastProviderStatus(v)
	return _u
}

// SetNillableLastProviderStatus sets the "last_provider_status" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableLastProviderStatus(v *string) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetLastProviderStatus(*v)
	}
	return _u
}

// ClearLastProviderStatus clears the value of the "last_provider_status" field.
func (_u *PaymentReconciliationUpdate) ClearLastProviderStatus() *PaymentReconciliationUpdate {
	_u.mutation.ClearLastProviderStatus()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PaymentReconciliationUpdate) SetLastError(v string) *PaymentReconciliationUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableLastError(v *string) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *PaymentReconciliationUpdate) ClearLastError() *PaymentReconciliationUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetProviderSnapshot sets the "provider_snapshot" field.
func (_u *PaymentReconciliationUpdate) SetProviderSnapshot(v map[string]interface{}) *PaymentReconciliationUpdate {
	_u.mutation.SetProviderSnapshot(v)
	return _u
}

// ClearProviderSnapshot clears the value of the "provider_snapshot" field.
func (_u *PaymentReconciliationUpdate) ClearProviderSnapshot() *PaymentReconciliationUpdate {
	_u.mutation.ClearProviderSnapshot()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *PaymentReconciliationUpdate) SetResolvedAt(v time.Time) *PaymentReconciliationUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *PaymentReconciliationUpdate) SetNillableResolvedAt(v *time.Time) *PaymentReconciliationUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *PaymentReconciliationUpdate) ClearResolvedAt() *PaymentReconciliationUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentReconciliationUpdate) SetUpdatedAt(v time.Time) *PaymentReconciliationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentReconciliationMutation object of the builder.
func (_u *PaymentReconciliationUpdate) Mutation() *PaymentReconciliationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentReconciliationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentReconciliationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentReconciliationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentReconciliationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentReconciliationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentreconciliation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PaymentReconciliationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentreconciliation.Table, paymentreconciliation.Columns, sqlgraph.NewFieldSpec(paymentreconciliation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(paymentreconciliation.FieldPaymentOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(paymentreconciliation.FieldPaymentOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GatewayOrderNo(); ok {
		_spec.SetField(paymentreconciliation.FieldGatewayOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(paymentreconciliation.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelAccountID(); ok {
		_spec.SetField(paymentreconciliation.FieldChannelAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChannelAccountID(); ok {
		_spec.AddField(paymentreconciliation.FieldChannelAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentreconciliation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(paymentreconciliation.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(paymentreconciliation.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(paymentreconciliation.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(paymentreconciliation.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(paymentreconciliation.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(paymentreconciliation.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProviderStatus(); ok {
		_spec.SetField(paymentreconciliation.FieldLastProviderStatus, field.TypeString, value)
	}
	if _u.mutation.LastProviderStatusCleared() {
		_spec.ClearField(paymentreconciliation.FieldLastProviderStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(paymentreconciliation.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(paymentreconciliation.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderSnapshot(); ok {
		_spec.SetField(paymentreconciliation.FieldProviderSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ProviderSnapshotCleared() {
		_spec.ClearField(paymentreconciliation.FieldProviderSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(paymentreconciliation.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(paymentreconciliation.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentreconciliation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentreconciliation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentReconciliationUpdateOne is the builder for updating a single PaymentReconciliation entity.
type PaymentReconciliationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentReconciliationMutation
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *PaymentReconciliationUpdateOne) SetPaymentOrderID(v int) *PaymentReconciliationUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillablePaymentOrderID(v *int) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *PaymentReconciliationUpdateOne) AddPaymentOrderID(v int) *PaymentReconciliationUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_u *PaymentReconciliationUpdateOne) SetGatewayOrderNo(v string) *PaymentReconciliationUpdateOne {
	_u.mutation.SetGatewayOrderNo(v)
	return _u
}

// SetNillableGatewayOrderNo sets the "gateway_order_no" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableGatewayOrderNo(v *string) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetGatewayOrderNo(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PaymentReconciliationUpdateOne) SetChannel(v string) *PaymentReconciliationUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableChannel(v *string) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetChannelAccountID sets the "channel_account_id" field.
func (_u *PaymentReconciliationUpdateOne) SetChannelAccountID(v int) *PaymentReconciliationUpdateOne {
	_u.mutation.ResetChannelAccountID()
	_u.mutation.SetChannelAccountID(v)
	return _u
}

// SetNillableChannelAccountID sets the "channel_account_id" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableChannelAccountID(v *int) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetChannelAccountID(*v)
	}
	return _u
}

// AddChannelAccountID adds value to the "channel_account_id" field.
func (_u *PaymentReconciliationUpdateOne) AddChannelAccountID(v int) *PaymentReconciliationUpdateOne {
	_u.mutation.AddChannelAccountID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentReconciliationUpdateOne) SetStatus(v string) *PaymentReconciliationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableStatus(v *string) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *PaymentReconciliationUpdateOne) SetAttemptCount(v int) *PaymentReconciliationUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableAttemptCount(v *int) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *PaymentReconciliationUpdateOne) AddAttemptCount(v int) *PaymentReconciliationUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PaymentReconciliationUpdateOne) SetNextAttemptAt(v time.Time) *PaymentReconciliationUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableNextAttemptAt(v *time.Time) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PaymentReconciliationUpdateOne) ClearNextAttemptAt() *PaymentReconciliationUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *PaymentReconciliationUpdateOne) SetLastAttemptAt(v time.Time) *PaymentReconciliationUpdateOne {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableLastAttemptAt(v *time.Time) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *PaymentReconciliationUpdateOne) ClearLastAttemptAt() *PaymentReconciliationUpdateOne {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetLastProviderStatus sets the "last_provider_status" field.
func (_u *PaymentReconciliationUpdateOne) SetLastProviderStatus(v string) *PaymentReconciliationUpdateOne {
	_u.mutation.SetLastProviderStatus(v)
	return _u
}

// SetNillableLastProviderStatus sets the "last_provider_status" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableLastProviderStatus(v *string) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetLastProviderStatus(*v)
	}
	return _u
}

// ClearLastProviderStatus clears the value of the "last_provider_status" field.
func (_u *PaymentReconciliationUpdateOne) ClearLastProviderStatus() *PaymentReconciliationUpdateOne {
	_u.mutation.ClearLastProviderStatus()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PaymentReconciliationUpdateOne) SetLastError(v string) *PaymentReconciliationUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableLastError(v *string) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *PaymentReconciliationUpdateOne) ClearLastError() *PaymentReconciliationUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetProviderSnapshot sets the "provider_snapshot" field.
func (_u *PaymentReconciliationUpdateOne) SetProviderSnapshot(v map[string]interface{}) *PaymentReconciliationUpdateOne {
	_u.mutation.SetProviderSnapshot(v)
	return _u
}

// ClearProviderSnapshot clears the value of the "provider_snapshot" field.
func (_u *PaymentReconciliationUpdateOne) ClearProviderSnapshot() *PaymentReconciliationUpdateOne {
	_u.mutation.ClearProviderSnapshot()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *PaymentReconciliationUpdateOne) SetResolvedAt(v time.Time) *PaymentReconciliationUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *PaymentReconciliationUpdateOne) SetNillableResolvedAt(v *time.Time) *PaymentReconciliationUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *PaymentReconciliationUpdateOne) ClearResolvedAt() *PaymentReconciliationUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentReconciliationUpdateOne) SetUpdatedAt(v time.Time) *PaymentReconciliationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentReconciliationMutation object of the builder.
func (_u *PaymentReconciliationUpdateOne) Mutation() *PaymentReconciliationMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentReconciliationUpdate builder.
func (_u *PaymentReconciliationUpdateOne) Where(ps ...predicate.PaymentReconciliation) *PaymentReconciliationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentReconciliationUpdateOne) Select(field string, fields ...string) *PaymentReconciliationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentReconciliation entity.
func (_u *PaymentReconciliationUpdateOne) Save(ctx context.Context) (*PaymentReconciliation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentReconciliationUpdateOne) SaveX(ctx context.Context) *PaymentReconciliation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentReconciliationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentReconciliationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentReconciliationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentreconciliation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PaymentReconciliationUpdateOne) sqlSave(ctx context.Context) (_node *PaymentReconciliation, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentreconciliation.Table, paymentreconciliation.Columns, sqlgraph.NewFieldSpec(paymentreconciliation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentReconciliation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentreconciliation.FieldID)
		for _, f := range fields {
			if !paymentreconciliation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentreconciliation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(paymentreconciliation.FieldPaymentOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(paymentreconciliation.FieldPaymentOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GatewayOrderNo(); ok {
		_spec.SetField(paymentreconciliation.FieldGatewayOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(paymentreconciliation.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelAccountID(); ok {
		_spec.SetField(paymentreconciliation.FieldChannelAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChannelAccountID(); ok {
		_spec.AddField(paymentreconciliation.FieldChannelAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentreconciliation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(paymentreconciliation.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(paymentreconciliation.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(paymentreconciliation.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(paymentreconciliation.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(paymentreconciliation.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(paymentreconciliation.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProviderStatus(); ok {
		_spec.SetField(paymentreconciliation.FieldLastProviderStatus, field.TypeString, value)
	}
	if _u.mutation.LastProviderStatusCleared() {
		_spec.ClearField(paymentreconciliation.FieldLastProviderStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(paymentreconciliation.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(paymentreconciliation.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderSnapshot(); ok {
		_spec.SetField(paymentreconciliation.FieldProviderSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ProviderSnapshotCleared() {
		_spec.ClearField(paymentreconciliation.FieldProviderSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(paymentreconciliation.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(paymentreconciliation.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentreconciliation.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentReconciliation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentreconciliation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
