// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"payment-gateway/ent/paymentreconciliation"
	"payment-gateway/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentReconciliationDelete is the builder for deleting a PaymentReconciliation entity.
type PaymentReconciliationDelete struct {
	config
	hooks    []Hook
	mutation *PaymentReconciliationMutation
}

// Where appends a list predicates to the PaymentReconciliationDelete builder.
func (_d *PaymentReconciliationDelete) Where(ps ...predicate.PaymentReconciliation) *PaymentReconciliationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentReconciliationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentReconciliationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentReconciliationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentreconciliation.Table, sqlgraph.NewFieldSpec(paymentreconciliation.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentReconciliationDeleteOne is the builder for deleting a single PaymentReconciliation entity.
type PaymentReconciliationDeleteOne struct {
	_d *PaymentReconciliationDelete
}

// Where appends a list predicates to the PaymentReconciliationDelete builder.
func (_d *PaymentReconciliationDeleteOne) Where(ps ...predicate.PaymentReconciliation) *PaymentReconciliationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentReconciliationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentreconciliation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentReconciliationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
