// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"payment-gateway/ent/routingrule"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoutingRuleCreate is the builder for creating a RoutingRule entity.
type RoutingRuleCreate struct {
	config
	mutation *RoutingRuleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RoutingRuleCreate) SetName(v string) *RoutingRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RoutingRuleCreate) SetEnabled(v bool) *RoutingRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableEnabled(v *bool) *RoutingRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *RoutingRuleCreate) SetPriority(v int) *RoutingRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillablePriority(v *int) *RoutingRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetAppScope sets the "app_scope" field.
func (_c *RoutingRuleCreate) SetAppScope(v string) *RoutingRuleCreate {
	_c.mutation.SetAppScope(v)
	return _c
}

// SetNillableAppScope sets the "app_scope" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableAppScope(v *string) *RoutingRuleCreate {
	if v != nil {
		_c.SetAppScope(*v)
	}
	return _c
}

// SetAppIds sets the "app_ids" field.
func (_c *RoutingRuleCreate) SetAppIds(v []string) *RoutingRuleCreate {
	_c.mutation.SetAppIds(v)
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *RoutingRuleCreate) SetPaymentMethod(v string) *RoutingRuleCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetPayModes sets the "pay_modes" field.
func (_c *RoutingRuleCreate) SetPayModes(v []string) *RoutingRuleCreate {
	_c.mutation.SetPayModes(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *RoutingRuleCreate) SetCurrency(v string) *RoutingRuleCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableCurrency(v *string) *RoutingRuleCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetMinAmount sets the "min_amount" field.
func (_c *RoutingRuleCreate) SetMinAmount(v int64) *RoutingRuleCreate {
	_c.mutation.SetMinAmount(v)
	return _c
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableMinAmount(v *int64) *RoutingRuleCreate {
	if v != nil {
		_c.SetMinAmount(*v)
	}
	return _c
}

// SetMaxAmount sets the "max_amount" field.
func (_c *RoutingRuleCreate) SetMaxAmount(v int64) *RoutingRuleCreate {
	_c.mutation.SetMaxAmount(v)
	return _c
}

// SetNillableMaxAmount sets the "max_amount" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableMaxAmount(v *int64) *RoutingRuleCreate {
	if v != nil {
		_c.SetMaxAmount(*v)
	}
	return _c
}

// SetTerminal sets the "terminal" field.
func (_c *RoutingRuleCreate) SetTerminal(v string) *RoutingRuleCreate {
	_c.mutation.SetTerminal(v)
	return _c
}

// SetNillableTerminal sets the "terminal" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableTerminal(v *string) *RoutingRuleCreate {
	if v != nil {
		_c.SetTerminal(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RoutingRuleCreate) SetMetadata(v map[string]interface{}) *RoutingRuleCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoutingRuleCreate) SetCreatedAt(v time.Time) *RoutingRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableCreatedAt(v *time.Time) *RoutingRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RoutingRuleCreate) SetUpdatedAt(v time.Time) *RoutingRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RoutingRuleCreate) SetNillableUpdatedAt(v *time.Time) *RoutingRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RoutingRuleMutation object of the builder.
func (_c *RoutingRuleCreate) Mutation() *RoutingRuleMutation {
	return _c.mutation
}

// Save creates the RoutingRule in the database.
func (_c *RoutingRuleCreate) Save(ctx context.Context) (*RoutingRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoutingRuleCreate) SaveX(ctx context.Context) *RoutingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoutingRuleCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := routingrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := routingrule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.AppScope(); !ok {
		v := routingrule.DefaultAppScope
		_c.mutation.SetAppScope(v)
	}
	if _, ok := _c.mutation.MinAmount(); !ok {
		v := routingrule.DefaultMinAmount
		_c.mutation.SetMinAmount(v)
	}
	if _, ok := _c.mutation.MaxAmount(); !ok {
		v := routingrule.DefaultMaxAmount
		_c.mutation.SetMaxAmount(v)
	}
	if _, ok := _c.mutation.Terminal(); !ok {
		v := routingrule.DefaultTerminal
		_c.mutation.SetTerminal(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := routingrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := routingrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoutingRuleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RoutingRule.name"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RoutingRule.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "RoutingRule.priority"`)}
	}
	if _, ok := _c.mutation.AppScope(); !ok {
		return &ValidationError{Name: "app_scope", err: errors.New(`ent: missing required field "RoutingRule.app_scope"`)}
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		return &ValidationError{Name: "payment_method", err: errors.New(`ent: missing required field "RoutingRule.payment_method"`)}
	}
	if _, ok := _c.mutation.MinAmount(); !ok {
		return &ValidationError{Name: "min_amount", err: errors.New(`ent: missing required field "RoutingRule.min_amount"`)}
	}
	if _, ok := _c.mutation.MaxAmount(); !ok {
		return &ValidationError{Name: "max_amount", err: errors.New(`ent: missing required field "RoutingRule.max_amount"`)}
	}
	if _, ok := _c.mutation.Terminal(); !ok {
		return &ValidationError{Name: "terminal", err: errors.New(`ent: missing required field "RoutingRule.terminal"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RoutingRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RoutingRule.updated_at"`)}
	}
	return nil
}

func (_c *RoutingRuleCreate) sqlSave(ctx context.Context) (*RoutingRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoutingRuleCreate) createSpec() (*RoutingRule, *sqlgraph.CreateSpec) {
	var (
		_node = &RoutingRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(routingrule.Table, sqlgraph.NewFieldSpec(routingrule.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(routingrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(routingrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(routingrule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.AppScope(); ok {
		_spec.SetField(routingrule.FieldAppScope, field.TypeString, value)
		_node.AppScope = value
	}
	if value, ok := _c.mutation.AppIds(); ok {
		_spec.SetField(routingrule.FieldAppIds, field.TypeJSON, value)
		_node.AppIds = value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(routingrule.FieldPaymentMethod, field.TypeString, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.PayModes(); ok {
		_spec.SetField(routingrule.FieldPayModes, field.TypeJSON, value)
		_node.PayModes = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(routingrule.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.MinAmount(); ok {
		_spec.SetField(routingrule.FieldMinAmount, field.TypeInt64, value)
		_node.MinAmount = value
	}
	if value, ok := _c.mutation.MaxAmount(); ok {
		_spec.SetField(routingrule.FieldMaxAmount, field.TypeInt64, value)
		_node.MaxAmount = value
	}
	if value, ok := _c.mutation.Terminal(); ok {
		_spec.SetField(routingrule.FieldTerminal, field.TypeString, value)
		_node.Terminal = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(routingrule.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(routingrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(routingrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RoutingRuleCreateBulk is the builder for creating many RoutingRule entities in bulk.
type RoutingRuleCreateBulk struct {
	config
	err      error
	builders []*RoutingRuleCreate
}

// Save creates the RoutingRule entities in the database.
func (_c *RoutingRuleCreateBulk) Save(ctx context.Context) ([]*RoutingRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoutingRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoutingRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoutingRuleCreateBulk) SaveX(ctx context.Context) []*RoutingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
