// Code generated by ent, DO NOT EDIT.

package ent

import (
	"payment-gateway/ent/app"
	"payment-gateway/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescStatus is the schema descriptor for status field.
	appDescStatus := appFields[4].Descriptor()
	// app.DefaultStatus holds the default value on creation for the status field.
	app.DefaultStatus = appDescStatus.Default.(string)
}
