// Code generated by ent, DO NOT EDIT.

package ent

import (
	"payment-gateway/ent/app"
	"payment-gateway/ent/channelaccount"
	"payment-gateway/ent/gatewayconfig"
	"payment-gateway/ent/paymentorder"
	"payment-gateway/ent/refreshtoken"
	"payment-gateway/ent/role"
	"payment-gateway/ent/schema"
	"payment-gateway/ent/user"
	"payment-gateway/ent/webhookdelivery"
	"payment-gateway/ent/webhookevent"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescStatus is the schema descriptor for status field.
	appDescStatus := appFields[7].Descriptor()
	// app.DefaultStatus holds the default value on creation for the status field.
	app.DefaultStatus = appDescStatus.Default.(string)
	// appDescCreatedAt is the schema descriptor for created_at field.
	appDescCreatedAt := appFields[8].Descriptor()
	// app.DefaultCreatedAt holds the default value on creation for the created_at field.
	app.DefaultCreatedAt = appDescCreatedAt.Default.(func() time.Time)
	// appDescUpdatedAt is the schema descriptor for updated_at field.
	appDescUpdatedAt := appFields[9].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	channelaccountFields := schema.ChannelAccount{}.Fields()
	_ = channelaccountFields
	// channelaccountDescEnabled is the schema descriptor for enabled field.
	channelaccountDescEnabled := channelaccountFields[2].Descriptor()
	// channelaccount.DefaultEnabled holds the default value on creation for the enabled field.
	channelaccount.DefaultEnabled = channelaccountDescEnabled.Default.(bool)
	// channelaccountDescEnv is the schema descriptor for env field.
	channelaccountDescEnv := channelaccountFields[3].Descriptor()
	// channelaccount.DefaultEnv holds the default value on creation for the env field.
	channelaccount.DefaultEnv = channelaccountDescEnv.Default.(string)
	// channelaccountDescCreatedAt is the schema descriptor for created_at field.
	channelaccountDescCreatedAt := channelaccountFields[5].Descriptor()
	// channelaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	channelaccount.DefaultCreatedAt = channelaccountDescCreatedAt.Default.(func() time.Time)
	// channelaccountDescUpdatedAt is the schema descriptor for updated_at field.
	channelaccountDescUpdatedAt := channelaccountFields[6].Descriptor()
	// channelaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	channelaccount.DefaultUpdatedAt = channelaccountDescUpdatedAt.Default.(func() time.Time)
	// channelaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channelaccount.UpdateDefaultUpdatedAt = channelaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewayconfigFields := schema.GatewayConfig{}.Fields()
	_ = gatewayconfigFields
	// gatewayconfigDescGatewayBaseURL is the schema descriptor for gateway_base_url field.
	gatewayconfigDescGatewayBaseURL := gatewayconfigFields[0].Descriptor()
	// gatewayconfig.DefaultGatewayBaseURL holds the default value on creation for the gateway_base_url field.
	gatewayconfig.DefaultGatewayBaseURL = gatewayconfigDescGatewayBaseURL.Default.(string)
	// gatewayconfigDescPaymentNotifyPath is the schema descriptor for payment_notify_path field.
	gatewayconfigDescPaymentNotifyPath := gatewayconfigFields[1].Descriptor()
	// gatewayconfig.DefaultPaymentNotifyPath holds the default value on creation for the payment_notify_path field.
	gatewayconfig.DefaultPaymentNotifyPath = gatewayconfigDescPaymentNotifyPath.Default.(string)
	// gatewayconfigDescDefaultCurrency is the schema descriptor for default_currency field.
	gatewayconfigDescDefaultCurrency := gatewayconfigFields[2].Descriptor()
	// gatewayconfig.DefaultDefaultCurrency holds the default value on creation for the default_currency field.
	gatewayconfig.DefaultDefaultCurrency = gatewayconfigDescDefaultCurrency.Default.(string)
	// gatewayconfigDescDefaultLocale is the schema descriptor for default_locale field.
	gatewayconfigDescDefaultLocale := gatewayconfigFields[3].Descriptor()
	// gatewayconfig.DefaultDefaultLocale holds the default value on creation for the default_locale field.
	gatewayconfig.DefaultDefaultLocale = gatewayconfigDescDefaultLocale.Default.(string)
	// gatewayconfigDescRequestIDEnabled is the schema descriptor for request_id_enabled field.
	gatewayconfigDescRequestIDEnabled := gatewayconfigFields[4].Descriptor()
	// gatewayconfig.DefaultRequestIDEnabled holds the default value on creation for the request_id_enabled field.
	gatewayconfig.DefaultRequestIDEnabled = gatewayconfigDescRequestIDEnabled.Default.(bool)
	// gatewayconfigDescMaintenanceMode is the schema descriptor for maintenance_mode field.
	gatewayconfigDescMaintenanceMode := gatewayconfigFields[5].Descriptor()
	// gatewayconfig.DefaultMaintenanceMode holds the default value on creation for the maintenance_mode field.
	gatewayconfig.DefaultMaintenanceMode = gatewayconfigDescMaintenanceMode.Default.(bool)
	// gatewayconfigDescCreatedAt is the schema descriptor for created_at field.
	gatewayconfigDescCreatedAt := gatewayconfigFields[7].Descriptor()
	// gatewayconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewayconfig.DefaultCreatedAt = gatewayconfigDescCreatedAt.Default.(func() time.Time)
	// gatewayconfigDescUpdatedAt is the schema descriptor for updated_at field.
	gatewayconfigDescUpdatedAt := gatewayconfigFields[8].Descriptor()
	// gatewayconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gatewayconfig.DefaultUpdatedAt = gatewayconfigDescUpdatedAt.Default.(func() time.Time)
	// gatewayconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gatewayconfig.UpdateDefaultUpdatedAt = gatewayconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	paymentorderFields := schema.PaymentOrder{}.Fields()
	_ = paymentorderFields
	// paymentorderDescStatus is the schema descriptor for status field.
	paymentorderDescStatus := paymentorderFields[15].Descriptor()
	// paymentorder.DefaultStatus holds the default value on creation for the status field.
	paymentorder.DefaultStatus = paymentorderDescStatus.Default.(string)
	// paymentorderDescCreatedAt is the schema descriptor for created_at field.
	paymentorderDescCreatedAt := paymentorderFields[20].Descriptor()
	// paymentorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentorder.DefaultCreatedAt = paymentorderDescCreatedAt.Default.(func() time.Time)
	// paymentorderDescUpdatedAt is the schema descriptor for updated_at field.
	paymentorderDescUpdatedAt := paymentorderFields[21].Descriptor()
	// paymentorder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentorder.DefaultUpdatedAt = paymentorderDescUpdatedAt.Default.(func() time.Time)
	// paymentorder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentorder.UpdateDefaultUpdatedAt = paymentorderDescUpdatedAt.UpdateDefault.(func() time.Time)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[6].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleFields[3].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(string)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[4].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[5].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[4].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	webhookdeliveryFields := schema.WebhookDelivery{}.Fields()
	_ = webhookdeliveryFields
	// webhookdeliveryDescStatus is the schema descriptor for status field.
	webhookdeliveryDescStatus := webhookdeliveryFields[6].Descriptor()
	// webhookdelivery.DefaultStatus holds the default value on creation for the status field.
	webhookdelivery.DefaultStatus = webhookdeliveryDescStatus.Default.(string)
	// webhookdeliveryDescAttemptCount is the schema descriptor for attempt_count field.
	webhookdeliveryDescAttemptCount := webhookdeliveryFields[7].Descriptor()
	// webhookdelivery.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	webhookdelivery.DefaultAttemptCount = webhookdeliveryDescAttemptCount.Default.(int)
	// webhookdeliveryDescCreatedAt is the schema descriptor for created_at field.
	webhookdeliveryDescCreatedAt := webhookdeliveryFields[14].Descriptor()
	// webhookdelivery.DefaultCreatedAt holds the default value on creation for the created_at field.
	webhookdelivery.DefaultCreatedAt = webhookdeliveryDescCreatedAt.Default.(func() time.Time)
	// webhookdeliveryDescUpdatedAt is the schema descriptor for updated_at field.
	webhookdeliveryDescUpdatedAt := webhookdeliveryFields[15].Descriptor()
	// webhookdelivery.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	webhookdelivery.DefaultUpdatedAt = webhookdeliveryDescUpdatedAt.Default.(func() time.Time)
	// webhookdelivery.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	webhookdelivery.UpdateDefaultUpdatedAt = webhookdeliveryDescUpdatedAt.UpdateDefault.(func() time.Time)
	webhookeventFields := schema.WebhookEvent{}.Fields()
	_ = webhookeventFields
	// webhookeventDescCreatedAt is the schema descriptor for created_at field.
	webhookeventDescCreatedAt := webhookeventFields[6].Descriptor()
	// webhookevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	webhookevent.DefaultCreatedAt = webhookeventDescCreatedAt.Default.(func() time.Time)
	// webhookeventDescUpdatedAt is the schema descriptor for updated_at field.
	webhookeventDescUpdatedAt := webhookeventFields[7].Descriptor()
	// webhookevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	webhookevent.DefaultUpdatedAt = webhookeventDescUpdatedAt.Default.(func() time.Time)
	// webhookevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	webhookevent.UpdateDefaultUpdatedAt = webhookeventDescUpdatedAt.UpdateDefault.(func() time.Time)
}
