// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"payment-gateway/ent/predicate"
	"payment-gateway/ent/webhookdelivery"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookDeliveryUpdate is the builder for updating WebhookDelivery entities.
type WebhookDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *WebhookDeliveryMutation
}

// Where appends a list predicates to the WebhookDeliveryUpdate builder.
func (_u *WebhookDeliveryUpdate) Where(ps ...predicate.WebhookDelivery) *WebhookDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeliveryNo sets the "delivery_no" field.
func (_u *WebhookDeliveryUpdate) SetDeliveryNo(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetDeliveryNo(v)
	return _u
}

// SetNillableDeliveryNo sets the "delivery_no" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableDeliveryNo(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetDeliveryNo(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *WebhookDeliveryUpdate) SetEventID(v int) *WebhookDeliveryUpdate {
	_u.mutation.ResetEventID()
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableEventID(v *int) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// AddEventID adds value to the "event_id" field.
func (_u *WebhookDeliveryUpdate) AddEventID(v int) *WebhookDeliveryUpdate {
	_u.mutation.AddEventID(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WebhookDeliveryUpdate) SetAppID(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableAppID(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *WebhookDeliveryUpdate) SetEventType(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableEventType(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *WebhookDeliveryUpdate) SetResourceType(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableResourceType(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *WebhookDeliveryUpdate) SetResourceID(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableResourceID(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_u *WebhookDeliveryUpdate) SetGatewayOrderNo(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetGatewayOrderNo(v)
	return _u
}

// SetNillableGatewayOrderNo sets the "gateway_order_no" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableGatewayOrderNo(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetGatewayOrderNo(*v)
	}
	return _u
}

// SetRefundNo sets the "refund_no" field.
func (_u *WebhookDeliveryUpdate) SetRefundNo(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetRefundNo(v)
	return _u
}

// SetNillableRefundNo sets the "refund_no" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableRefundNo(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetRefundNo(*v)
	}
	return _u
}

// ClearRefundNo clears the value of the "refund_no" field.
func (_u *WebhookDeliveryUpdate) ClearRefundNo() *WebhookDeliveryUpdate {
	_u.mutation.ClearRefundNo()
	return _u
}

// SetTargetURL sets the "target_url" field.
func (_u *WebhookDeliveryUpdate) SetTargetURL(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetTargetURL(v)
	return _u
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableTargetURL(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetTargetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WebhookDeliveryUpdate) SetStatus(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableStatus(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *WebhookDeliveryUpdate) SetAttemptCount(v int) *WebhookDeliveryUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableAttemptCount(v *int) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *WebhookDeliveryUpdate) AddAttemptCount(v int) *WebhookDeliveryUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *WebhookDeliveryUpdate) SetNextAttemptAt(v time.Time) *WebhookDeliveryUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableNextAttemptAt(v *time.Time) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *WebhookDeliveryUpdate) ClearNextAttemptAt() *WebhookDeliveryUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *WebhookDeliveryUpdate) SetLastAttemptAt(v time.Time) *WebhookDeliveryUpdate {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableLastAttemptAt(v *time.Time) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *WebhookDeliveryUpdate) ClearLastAttemptAt() *WebhookDeliveryUpdate {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetLastStatusCode sets the "last_status_code" field.
func (_u *WebhookDeliveryUpdate) SetLastStatusCode(v int) *WebhookDeliveryUpdate {
	_u.mutation.ResetLastStatusCode()
	_u.mutation.SetLastStatusCode(v)
	return _u
}

// SetNillableLastStatusCode sets the "last_status_code" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableLastStatusCode(v *int) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetLastStatusCode(*v)
	}
	return _u
}

// AddLastStatusCode adds value to the "last_status_code" field.
func (_u *WebhookDeliveryUpdate) AddLastStatusCode(v int) *WebhookDeliveryUpdate {
	_u.mutation.AddLastStatusCode(v)
	return _u
}

// ClearLastStatusCode clears the value of the "last_status_code" field.
func (_u *WebhookDeliveryUpdate) ClearLastStatusCode() *WebhookDeliveryUpdate {
	_u.mutation.ClearLastStatusCode()
	return _u
}

// SetLastResponseBody sets the "last_response_body" field.
func (_u *WebhookDeliveryUpdate) SetLastResponseBody(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetLastResponseBody(v)
	return _u
}

// SetNillableLastResponseBody sets the "last_response_body" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableLastResponseBody(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetLastResponseBody(*v)
	}
	return _u
}

// ClearLastResponseBody clears the value of the "last_response_body" field.
func (_u *WebhookDeliveryUpdate) ClearLastResponseBody() *WebhookDeliveryUpdate {
	_u.mutation.ClearLastResponseBody()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *WebhookDeliveryUpdate) SetLastError(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableLastError(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *WebhookDeliveryUpdate) ClearLastError() *WebhookDeliveryUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetSucceededAt sets the "succeeded_at" field.
func (_u *WebhookDeliveryUpdate) SetSucceededAt(v time.Time) *WebhookDeliveryUpdate {
	_u.mutation.SetSucceededAt(v)
	return _u
}

// SetNillableSucceededAt sets the "succeeded_at" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableSucceededAt(v *time.Time) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetSucceededAt(*v)
	}
	return _u
}

// ClearSucceededAt clears the value of the "succeeded_at" field.
func (_u *WebhookDeliveryUpdate) ClearSucceededAt() *WebhookDeliveryUpdate {
	_u.mutation.ClearSucceededAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebhookDeliveryUpdate) SetUpdatedAt(v time.Time) *WebhookDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (_u *WebhookDeliveryUpdate) Mutation() *WebhookDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebhookDeliveryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebhookDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebhookDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebhookDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebhookDeliveryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := webhookdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WebhookDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(webhookdelivery.Table, webhookdelivery.Columns, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeliveryNo(); ok {
		_spec.SetField(webhookdelivery.FieldDeliveryNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(webhookdelivery.FieldEventID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventID(); ok {
		_spec.AddField(webhookdelivery.FieldEventID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(webhookdelivery.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(webhookdelivery.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(webhookdelivery.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(webhookdelivery.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayOrderNo(); ok {
		_spec.SetField(webhookdelivery.FieldGatewayOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundNo(); ok {
		_spec.SetField(webhookdelivery.FieldRefundNo, field.TypeString, value)
	}
	if _u.mutation.RefundNoCleared() {
		_spec.ClearField(webhookdelivery.FieldRefundNo, field.TypeString)
	}
	if value, ok := _u.mutation.TargetURL(); ok {
		_spec.SetField(webhookdelivery.FieldTargetURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(webhookdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(webhookdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(webhookdelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(webhookdelivery.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(webhookdelivery.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(webhookdelivery.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastStatusCode(); ok {
		_spec.SetField(webhookdelivery.FieldLastStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastStatusCode(); ok {
		_spec.AddField(webhookdelivery.FieldLastStatusCode, field.TypeInt, value)
	}
	if _u.mutation.LastStatusCodeCleared() {
		_spec.ClearField(webhookdelivery.FieldLastStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.LastResponseBody(); ok {
		_spec.SetField(webhookdelivery.FieldLastResponseBody, field.TypeString, value)
	}
	if _u.mutation.LastResponseBodyCleared() {
		_spec.ClearField(webhookdelivery.FieldLastResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(webhookdelivery.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(webhookdelivery.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SucceededAt(); ok {
		_spec.SetField(webhookdelivery.FieldSucceededAt, field.TypeTime, value)
	}
	if _u.mutation.SucceededAtCleared() {
		_spec.ClearField(webhookdelivery.FieldSucceededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhookdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebhookDeliveryUpdateOne is the builder for updating a single WebhookDelivery entity.
type WebhookDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebhookDeliveryMutation
}

// SetDeliveryNo sets the "delivery_no" field.
func (_u *WebhookDeliveryUpdateOne) SetDeliveryNo(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetDeliveryNo(v)
	return _u
}

// SetNillableDeliveryNo sets the "delivery_no" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableDeliveryNo(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetDeliveryNo(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *WebhookDeliveryUpdateOne) SetEventID(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.ResetEventID()
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableEventID(v *int) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// AddEventID adds value to the "event_id" field.
func (_u *WebhookDeliveryUpdateOne) AddEventID(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.AddEventID(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WebhookDeliveryUpdateOne) SetAppID(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableAppID(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *WebhookDeliveryUpdateOne) SetEventType(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableEventType(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *WebhookDeliveryUpdateOne) SetResourceType(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableResourceType(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *WebhookDeliveryUpdateOne) SetResourceID(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableResourceID(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_u *WebhookDeliveryUpdateOne) SetGatewayOrderNo(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetGatewayOrderNo(v)
	return _u
}

// SetNillableGatewayOrderNo sets the "gateway_order_no" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableGatewayOrderNo(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetGatewayOrderNo(*v)
	}
	return _u
}

// SetRefundNo sets the "refund_no" field.
func (_u *WebhookDeliveryUpdateOne) SetRefundNo(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetRefundNo(v)
	return _u
}

// SetNillableRefundNo sets the "refund_no" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableRefundNo(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetRefundNo(*v)
	}
	return _u
}

// ClearRefundNo clears the value of the "refund_no" field.
func (_u *WebhookDeliveryUpdateOne) ClearRefundNo() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearRefundNo()
	return _u
}

// SetTargetURL sets the "target_url" field.
func (_u *WebhookDeliveryUpdateOne) SetTargetURL(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetTargetURL(v)
	return _u
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableTargetURL(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetTargetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WebhookDeliveryUpdateOne) SetStatus(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableStatus(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *WebhookDeliveryUpdateOne) SetAttemptCount(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableAttemptCount(v *int) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *WebhookDeliveryUpdateOne) AddAttemptCount(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *WebhookDeliveryUpdateOne) SetNextAttemptAt(v time.Time) *WebhookDeliveryUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableNextAttemptAt(v *time.Time) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *WebhookDeliveryUpdateOne) ClearNextAttemptAt() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *WebhookDeliveryUpdateOne) SetLastAttemptAt(v time.Time) *WebhookDeliveryUpdateOne {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableLastAttemptAt(v *time.Time) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *WebhookDeliveryUpdateOne) ClearLastAttemptAt() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetLastStatusCode sets the "last_status_code" field.
func (_u *WebhookDeliveryUpdateOne) SetLastStatusCode(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.ResetLastStatusCode()
	_u.mutation.SetLastStatusCode(v)
	return _u
}

// SetNillableLastStatusCode sets the "last_status_code" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableLastStatusCode(v *int) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetLastStatusCode(*v)
	}
	return _u
}

// AddLastStatusCode adds value to the "last_status_code" field.
func (_u *WebhookDeliveryUpdateOne) AddLastStatusCode(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.AddLastStatusCode(v)
	return _u
}

// ClearLastStatusCode clears the value of the "last_status_code" field.
func (_u *WebhookDeliveryUpdateOne) ClearLastStatusCode() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearLastStatusCode()
	return _u
}

// SetLastResponseBody sets the "last_response_body" field.
func (_u *WebhookDeliveryUpdateOne) SetLastResponseBody(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetLastResponseBody(v)
	return _u
}

// SetNillableLastResponseBody sets the "last_response_body" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableLastResponseBody(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetLastResponseBody(*v)
	}
	return _u
}

// ClearLastResponseBody clears the value of the "last_response_body" field.
func (_u *WebhookDeliveryUpdateOne) ClearLastResponseBody() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearLastResponseBody()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *WebhookDeliveryUpdateOne) SetLastError(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableLastError(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *WebhookDeliveryUpdateOne) ClearLastError() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetSucceededAt sets the "succeeded_at" field.
func (_u *WebhookDeliveryUpdateOne) SetSucceededAt(v time.Time) *WebhookDeliveryUpdateOne {
	_u.mutation.SetSucceededAt(v)
	return _u
}

// SetNillableSucceededAt sets the "succeeded_at" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableSucceededAt(v *time.Time) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetSucceededAt(*v)
	}
	return _u
}

// ClearSucceededAt clears the value of the "succeeded_at" field.
func (_u *WebhookDeliveryUpdateOne) ClearSucceededAt() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearSucceededAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebhookDeliveryUpdateOne) SetUpdatedAt(v time.Time) *WebhookDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (_u *WebhookDeliveryUpdateOne) Mutation() *WebhookDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the WebhookDeliveryUpdate builder.
func (_u *WebhookDeliveryUpdateOne) Where(ps ...predicate.WebhookDelivery) *WebhookDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebhookDeliveryUpdateOne) Select(field string, fields ...string) *WebhookDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebhookDelivery entity.
func (_u *WebhookDeliveryUpdateOne) Save(ctx context.Context) (*WebhookDelivery, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebhookDeliveryUpdateOne) SaveX(ctx context.Context) *WebhookDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebhookDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebhookDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebhookDeliveryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := webhookdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WebhookDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *WebhookDelivery, err error) {
	_spec := sqlgraph.NewUpdateSpec(webhookdelivery.Table, webhookdelivery.Columns, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebhookDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhookdelivery.FieldID)
		for _, f := range fields {
			if !webhookdelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webhookdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeliveryNo(); ok {
		_spec.SetField(webhookdelivery.FieldDeliveryNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(webhookdelivery.FieldEventID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventID(); ok {
		_spec.AddField(webhookdelivery.FieldEventID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(webhookdelivery.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(webhookdelivery.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(webhookdelivery.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(webhookdelivery.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayOrderNo(); ok {
		_spec.SetField(webhookdelivery.FieldGatewayOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundNo(); ok {
		_spec.SetField(webhookdelivery.FieldRefundNo, field.TypeString, value)
	}
	if _u.mutation.RefundNoCleared() {
		_spec.ClearField(webhookdelivery.FieldRefundNo, field.TypeString)
	}
	if value, ok := _u.mutation.TargetURL(); ok {
		_spec.SetField(webhookdelivery.FieldTargetURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(webhookdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(webhookdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(webhookdelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(webhookdelivery.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(webhookdelivery.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(webhookdelivery.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastStatusCode(); ok {
		_spec.SetField(webhookdelivery.FieldLastStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastStatusCode(); ok {
		_spec.AddField(webhookdelivery.FieldLastStatusCode, field.TypeInt, value)
	}
	if _u.mutation.LastStatusCodeCleared() {
		_spec.ClearField(webhookdelivery.FieldLastStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.LastResponseBody(); ok {
		_spec.SetField(webhookdelivery.FieldLastResponseBody, field.TypeString, value)
	}
	if _u.mutation.LastResponseBodyCleared() {
		_spec.ClearField(webhookdelivery.FieldLastResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(webhookdelivery.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(webhookdelivery.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SucceededAt(); ok {
		_spec.SetField(webhookdelivery.FieldSucceededAt, field.TypeTime, value)
	}
	if _u.mutation.SucceededAtCleared() {
		_spec.ClearField(webhookdelivery.FieldSucceededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &WebhookDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhookdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
