// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"payment-gateway/ent/webhookevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookEventCreate is the builder for creating a WebhookEvent entity.
type WebhookEventCreate struct {
	config
	mutation *WebhookEventMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *WebhookEventCreate) SetEventID(v string) *WebhookEventCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *WebhookEventCreate) SetEventType(v string) *WebhookEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *WebhookEventCreate) SetAppID(v string) *WebhookEventCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_c *WebhookEventCreate) SetGatewayOrderNo(v string) *WebhookEventCreate {
	_c.mutation.SetGatewayOrderNo(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *WebhookEventCreate) SetPaymentOrderID(v int) *WebhookEventCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *WebhookEventCreate) SetNillablePaymentOrderID(v *int) *WebhookEventCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *WebhookEventCreate) SetPayload(v map[string]interface{}) *WebhookEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebhookEventCreate) SetCreatedAt(v time.Time) *WebhookEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebhookEventCreate) SetNillableCreatedAt(v *time.Time) *WebhookEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebhookEventCreate) SetUpdatedAt(v time.Time) *WebhookEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebhookEventCreate) SetNillableUpdatedAt(v *time.Time) *WebhookEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the WebhookEventMutation object of the builder.
func (_c *WebhookEventCreate) Mutation() *WebhookEventMutation {
	return _c.mutation
}

// Save creates the WebhookEvent in the database.
func (_c *WebhookEventCreate) Save(ctx context.Context) (*WebhookEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookEventCreate) SaveX(ctx context.Context) *WebhookEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webhookevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := webhookevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookEventCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "WebhookEvent.event_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "WebhookEvent.event_type"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "WebhookEvent.app_id"`)}
	}
	if _, ok := _c.mutation.GatewayOrderNo(); !ok {
		return &ValidationError{Name: "gateway_order_no", err: errors.New(`ent: missing required field "WebhookEvent.gateway_order_no"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebhookEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WebhookEvent.updated_at"`)}
	}
	return nil
}

func (_c *WebhookEventCreate) sqlSave(ctx context.Context) (*WebhookEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookEventCreate) createSpec() (*WebhookEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &WebhookEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhookevent.Table, sqlgraph.NewFieldSpec(webhookevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(webhookevent.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(webhookevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(webhookevent.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.GatewayOrderNo(); ok {
		_spec.SetField(webhookevent.FieldGatewayOrderNo, field.TypeString, value)
		_node.GatewayOrderNo = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(webhookevent.FieldPaymentOrderID, field.TypeInt, value)
		_node.PaymentOrderID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(webhookevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webhookevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webhookevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// WebhookEventCreateBulk is the builder for creating many WebhookEvent entities in bulk.
type WebhookEventCreateBulk struct {
	config
	err      error
	builders []*WebhookEventCreate
}

// Save creates the WebhookEvent entities in the database.
func (_c *WebhookEventCreateBulk) Save(ctx context.Context) ([]*WebhookEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebhookEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookEventCreateBulk) SaveX(ctx context.Context) []*WebhookEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
