// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"payment-gateway/ent/webhookdelivery"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookDeliveryCreate is the builder for creating a WebhookDelivery entity.
type WebhookDeliveryCreate struct {
	config
	mutation *WebhookDeliveryMutation
	hooks    []Hook
}

// SetDeliveryNo sets the "delivery_no" field.
func (_c *WebhookDeliveryCreate) SetDeliveryNo(v string) *WebhookDeliveryCreate {
	_c.mutation.SetDeliveryNo(v)
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *WebhookDeliveryCreate) SetEventID(v int) *WebhookDeliveryCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *WebhookDeliveryCreate) SetAppID(v string) *WebhookDeliveryCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *WebhookDeliveryCreate) SetEventType(v string) *WebhookDeliveryCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetGatewayOrderNo sets the "gateway_order_no" field.
func (_c *WebhookDeliveryCreate) SetGatewayOrderNo(v string) *WebhookDeliveryCreate {
	_c.mutation.SetGatewayOrderNo(v)
	return _c
}

// SetTargetURL sets the "target_url" field.
func (_c *WebhookDeliveryCreate) SetTargetURL(v string) *WebhookDeliveryCreate {
	_c.mutation.SetTargetURL(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WebhookDeliveryCreate) SetStatus(v string) *WebhookDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableStatus(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *WebhookDeliveryCreate) SetAttemptCount(v int) *WebhookDeliveryCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableAttemptCount(v *int) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *WebhookDeliveryCreate) SetNextAttemptAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableNextAttemptAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_c *WebhookDeliveryCreate) SetLastAttemptAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetLastAttemptAt(v)
	return _c
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableLastAttemptAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetLastAttemptAt(*v)
	}
	return _c
}

// SetLastStatusCode sets the "last_status_code" field.
func (_c *WebhookDeliveryCreate) SetLastStatusCode(v int) *WebhookDeliveryCreate {
	_c.mutation.SetLastStatusCode(v)
	return _c
}

// SetNillableLastStatusCode sets the "last_status_code" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableLastStatusCode(v *int) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetLastStatusCode(*v)
	}
	return _c
}

// SetLastResponseBody sets the "last_response_body" field.
func (_c *WebhookDeliveryCreate) SetLastResponseBody(v string) *WebhookDeliveryCreate {
	_c.mutation.SetLastResponseBody(v)
	return _c
}

// SetNillableLastResponseBody sets the "last_response_body" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableLastResponseBody(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetLastResponseBody(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *WebhookDeliveryCreate) SetLastError(v string) *WebhookDeliveryCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableLastError(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetSucceededAt sets the "succeeded_at" field.
func (_c *WebhookDeliveryCreate) SetSucceededAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetSucceededAt(v)
	return _c
}

// SetNillableSucceededAt sets the "succeeded_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableSucceededAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetSucceededAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebhookDeliveryCreate) SetCreatedAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableCreatedAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebhookDeliveryCreate) SetUpdatedAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableUpdatedAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (_c *WebhookDeliveryCreate) Mutation() *WebhookDeliveryMutation {
	return _c.mutation
}

// Save creates the WebhookDelivery in the database.
func (_c *WebhookDeliveryCreate) Save(ctx context.Context) (*WebhookDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookDeliveryCreate) SaveX(ctx context.Context) *WebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := webhookdelivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := webhookdelivery.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webhookdelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := webhookdelivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookDeliveryCreate) check() error {
	if _, ok := _c.mutation.DeliveryNo(); !ok {
		return &ValidationError{Name: "delivery_no", err: errors.New(`ent: missing required field "WebhookDelivery.delivery_no"`)}
	}
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "WebhookDelivery.event_id"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "WebhookDelivery.app_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "WebhookDelivery.event_type"`)}
	}
	if _, ok := _c.mutation.GatewayOrderNo(); !ok {
		return &ValidationError{Name: "gateway_order_no", err: errors.New(`ent: missing required field "WebhookDelivery.gateway_order_no"`)}
	}
	if _, ok := _c.mutation.TargetURL(); !ok {
		return &ValidationError{Name: "target_url", err: errors.New(`ent: missing required field "WebhookDelivery.target_url"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WebhookDelivery.status"`)}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "WebhookDelivery.attempt_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebhookDelivery.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WebhookDelivery.updated_at"`)}
	}
	return nil
}

func (_c *WebhookDeliveryCreate) sqlSave(ctx context.Context) (*WebhookDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookDeliveryCreate) createSpec() (*WebhookDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &WebhookDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhookdelivery.Table, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeliveryNo(); ok {
		_spec.SetField(webhookdelivery.FieldDeliveryNo, field.TypeString, value)
		_node.DeliveryNo = value
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(webhookdelivery.FieldEventID, field.TypeInt, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(webhookdelivery.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(webhookdelivery.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.GatewayOrderNo(); ok {
		_spec.SetField(webhookdelivery.FieldGatewayOrderNo, field.TypeString, value)
		_node.GatewayOrderNo = value
	}
	if value, ok := _c.mutation.TargetURL(); ok {
		_spec.SetField(webhookdelivery.FieldTargetURL, field.TypeString, value)
		_node.TargetURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(webhookdelivery.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(webhookdelivery.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = &value
	}
	if value, ok := _c.mutation.LastAttemptAt(); ok {
		_spec.SetField(webhookdelivery.FieldLastAttemptAt, field.TypeTime, value)
		_node.LastAttemptAt = &value
	}
	if value, ok := _c.mutation.LastStatusCode(); ok {
		_spec.SetField(webhookdelivery.FieldLastStatusCode, field.TypeInt, value)
		_node.LastStatusCode = value
	}
	if value, ok := _c.mutation.LastResponseBody(); ok {
		_spec.SetField(webhookdelivery.FieldLastResponseBody, field.TypeString, value)
		_node.LastResponseBody = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(webhookdelivery.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.SucceededAt(); ok {
		_spec.SetField(webhookdelivery.FieldSucceededAt, field.TypeTime, value)
		_node.SucceededAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// WebhookDeliveryCreateBulk is the builder for creating many WebhookDelivery entities in bulk.
type WebhookDeliveryCreateBulk struct {
	config
	err      error
	builders []*WebhookDeliveryCreate
}

// Save creates the WebhookDelivery entities in the database.
func (_c *WebhookDeliveryCreateBulk) Save(ctx context.Context) ([]*WebhookDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebhookDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookDeliveryCreateBulk) SaveX(ctx context.Context) []*WebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
